#!/usr/bin/env bash 

set -e 

display_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --conf-file FILE, -e FILE   Path to .conf formatted configuration file."    
    echo "  --help, -h                    Displays this help text and exits."
    echo "  --version, -v                 Displays the version and exits."
    exit 0
}

display_version() {
    local version=$(basename "$(dirname "$(realpath "$0")")")
    echo "$0 version $version"
    exit 0
}

CONFIG_FILES=()
HELP=false
VERSION=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --conf-file|-e)
            CONFIG_FILES+=("$2")
            shift 2
            ;;
        --help|-h)
            HELP=true
            shift
            ;;
        --version|-v)
            VERSION=true
            shift
            ;;  
        *)
            echo "Error: Unknown option $1"
            display_help
            ;;
    esac
done

if [ "$HELP" = true ]; then
    display_help
fi

if [ "$VERSION" = true ]; then
    display_version
fi

if [[ ${#CONFIG_FILES[@]} -eq 0 ]]; then
    echo "Error: At least one --conf-file option is required"
    display_help
fi

for CONFIG_FILE in "${CONFIG_FILES[@]}"; do
    if [[ -f "$CONFIG_FILE" ]]; then
        echo "Starting with configuration from $CONFIG_FILE"
        source "$CONFIG_FILE"
    else
        echo "Error: Configuration file $CONFIG_FILE not found."
        exit 1
    fi
done

echo "Starting with configuration from $CONFIG_FILE"

OPTIONS=""

append_option() {
  local option=$1
  local value=$2
  if [ -n "$value" ]; then
    OPTIONS="$OPTIONS $option=$value"
  fi
}

append_flag(){
 local option=$1
  local value=$2
  if [ "$value" = "true" ]; then
    OPTIONS="$OPTIONS $option"
  fi 
}

append_option "--data-dir" "$NIMBUS_ETH2_CLI_VALIDATOR_DATADIR"
append_option "--validators-dir" "$NIMBUS_ETH2_CLI_VALIDATOR_VALIDATORS_DIR"
append_option "--secrets-dir" "$NIMBUS_ETH2_CLI_VALIDATOR_SECRETS_DIR"
append_option "--beacon-node" "$NIMBUS_ETH2_CLI_VALIDATOR_BEACON_NODE"
append_option "--suggested-fee-recipient" "$NIMBUS_ETH2_CLI_VALIDATOR_SUGGESTED_FEE_RECIPIENT"


echo "Using Options /usr/lib/eth-node-nimbus-eth2/bin/validator: $OPTIONS"

# TODO generated by hand, need to fix this
# /usr/lib/eth-node-nimbus-eth2/bin/nimbus_beacon_node deposits import \
#    "/var/lib/eth-node-regtest/nimbus-eth2-validator/keys" \
#   --data-dir:/var/lib/eth-node-regtest/nimbus-eth2-validator 

# TODO 
exec /usr/lib/eth-node-nimbus-eth2/bin/nimbus_validator_client $OPTIONS