#!/bin/bash
set -e

. /usr/share/debconf/confmodule

declare -A CONFIG

adduser --system --quiet --group eth-node-mainnet-service-nethermind 
mkdir -p /var/lib/eth-node-mainnet/nethermind
chown eth-node-mainnet-service-nethermind:eth-node-mainnet-service-nethermind /var/lib/eth-node-mainnet/nethermind 

mkdir -p /var/lib/eth-node-mainnet/besu
jwt_file=/etc/eth-node-mainnet/jwt.hex
if [ ! -f "$jwt_file" ]; then
	openssl rand -hex 32 | tr -d "\n" | tee "$jwt_file" >/dev/null
fi

if [ "$1" = triggered -a "$service_was_running" '!=' 0 ];
then
	deb-systemd-invoke restart eth-node-mainnet-service-nethermind
fi

if [ "$1" '!=' triggered ];
then
	dpkg-trigger eth-node-mainnet-service-nethermind-config-changed

fi
#DEBHELPER#

exit 0
