#!/bin/bash
set -e

. /usr/share/debconf/confmodule

declare -A CONFIG

adduser --system --quiet --group eth-node-mainnet-service-ligthhouse 
mkdir -p /var/lib/eth-node-mainnet/ligthhouse
chown eth-node-mainnet-service-ligthhouse:eth-node-mainnet-service-ligthhouse /var/lib/eth-node-mainnet/ligthhouse 

if [ "$1" = triggered -a "$service_was_running" '!=' 0 ];
then
	deb-systemd-invoke restart eth-node-mainnet-service-ligthhouse
fi

if [ "$1" '!=' triggered ];
then
	dpkg-trigger eth-node-mainnet-service-ligthhouse-config-changed

fi
#DEBHELPER#

exit 0
