#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which geth)"
  assertEquals "/usr/bin/geth" "$output"
}

test_invocation(){
  output="$(geth --version)"
  echo "$output"
  # check against
  # https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-amd64-1.13.4-3f907d6a.tar.gz
  assertEquals "geth version 1.14.6-stable" "$output"
}

. shunit2
