#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which nethermind)"
  assertEquals "/usr/bin/nethermind" "$output"
}

test_invocation_with_dotnet(){
  output="$(nethermind --version)"
  echo "$output"
  # checked against https://github.com/NethermindEth/nethermind/releases/download/1.21.1/nethermind-1.21.1-9b435ba0-linux-x64.zip
  assertContains "$output" "Version: 1.21.1+Nethermi
Commit: Nethermind
Build Date: 2024-04-25 04:56:03Z
OS: Linux x64
Runtime: .NET 7.0.18
"
}

. shunit2