[package_fields]
spec_file = "eth-node-besu.sss"
package_name = "eth-node-besu"
version_number = "25.7.0"
revision_number = "1"
homepage = "https://github.com/hyperledger/besu"

[package_type]
# virtual | git | default
package_type = "default"
tarball_url = "https://github.com/hyperledger/besu/archive/refs/tags/25.7.0.tar.gz"
tarball_hash = "5037529c6450a19444e23c2163b57c0ccf39d1e62645a4a380cc2a42f0434bc7"

[package_type.language_env]
language_env = "java"
is_oracle = true
jdk_version = "21.0"
jdk_binary_url = "https://download.oracle.com/java/21/archive/jdk-21.0.6_linux-x64_bin.tar.gz"
jdk_binary_checksum = "e6a8125085949cb6c9fb823c79ed009a0ef24c878662c02fcb5ae890375e5a38"

[package_type.language_env.gradle]
# Gradle 7.6 downloads itself, even if it's the current version is right...
gradle_version = "8.14"
gradle_binary_url = "https://github.com/gradle/gradle-distributions/releases/download/v8.14.0/gradle-8.14-bin.zip"
gradle_binary_checksum = "61ad310d3c7d3e5da131b76bbf22b5a4c0786e9d892dae8c1658d4b484de3caa"

[build_env]
codename = "bookworm"
arch = "amd64"
pkg_builder_version = "0.3.1"
debcrafter_version = "8189263"
run_lintian = true
run_piuparts = true
run_autopkgtest = true
lintian_version = "2.116.3"
piuparts_version = "1.1.7"
autopkgtest_version = "5.28"
sbuild_version = "0.85.6"
# package directory
workdir = "~/.pkg-builder/packages/bookworm"
