#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.3.1
Commit SHA: 8142c6c327e6462f2f6a009036bc5c585afc52a0
Build Timestamp: 2025-03-14T17:39Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

