[package_fields]
spec_file = "eth-node-reth.sss"
package_name = "eth-node-reth"
version_number = "1.3.2"
revision_number = "1"
homepage="https://github.com/paradigmxyz/reth"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/paradigmxyz/reth/archive/refs/tags/v1.3.2.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "175a7dccc3caea90ac0c0daf608b47d866b138c073e8396412d947d36c3ccb15"

[package_type.language_env]
language_env = "rust"
rust_version="1.85.0"
rust_binary_url="https://static.rust-lang.org/dist/rust-1.85.0-x86_64-unknown-linux-gnu.tar.xz"
rust_binary_gpg_asc="""
-----BEGIN PGP SIGNATURE-----

wsFcBAABCgAQBQJnt1zZCRCFq5bm+hvl/gAAUu4P/jvAb5c73DqSDtts10mV8qRm
ihujHgWVVjm0l9Gzx9ii2qWSjJS/CNZ3BOZXckX9THX1raLP0Nem0ngSb/JTIvq7
9BRq/Q0rgPvttqhTkraeXpuQkbOCwzx0+O55edZTtcATkTGoLmVc8mkLmB837saV
LDF7nfSGi4pO3MtHyKJ9P49JPVPnQ8KbwdBvH6vXdVINjqrziFKr+QXKD7dd5f3w
R21OtmZJFpwsu9HVGgat1+/qTcMhbZWnerPkg/0pIV/xJJjvukk2GPB2hfXBNqF/
+9OqHfRgP5ATE4qVJ/AdeecMckLLYLeF/R2gR8lPemaNZf0nmo7tcqu0M39CiJF/
25tUvQLCXg5clAEWM+9qW7S0f23d7Vi/KvHpv0aUMvAg6Lc/OOFC8M9/hcDd5Jcs
FTTKSk/4Kji+jjsDvr9oJNSc3cFWYtzEGgG4AFjnv+bz0Lpnm4fTHjAYuf5BWzve
3q7VeNpnGPr8ftf2j/7U64x7abhzgQYcoYwt0nGvGvDrr9LErs7VuNpO/A7q8j+b
uKk+hA9icFV6xD5P9ZjTxukL7J80IE1YuYDdqIsdV27j0RggzXfX9SsPoUXzvP65
L1W4UXYRDX5itEEI7nRyntcqzqeV+rePoJUalme4gFaH/7W2pVODFD7XVI9o4qNT
gP1jBnXOKzeB8EhLxZjd
=SDX2
-----END PGP SIGNATURE-----
"""

[build_env]
codename="noble numbat"
arch = "amd64"
pkg_builder_version="0.2.11"
debcrafter_version = "2711b53"
# needed for tests
docker=true
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/noble"
