[package_fields]
spec_file = "eth-node-nethermind.sss"
package_name = "eth-node-nethermind"
version_number = "1.30.2"
revision_number = "1"
homepage = "https://github.com/NethermindEth/nethermind"

[package_type]
# virtual | git | default
package_type = "default"
tarball_url = "https://github.com/NethermindEth/nethermind/archive/refs/tags/1.30.2.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "e2d403862038246fff4295558af3f7dcf147dd248d151cf08663687100c159be"

[package_type.language_env]
language_env="dotnet"
## because MS force pushes package version
dotnet_packages  = [
    { name = "aspnetcore-runtime-9.0_9.0.0-1_amd64", hash = "2031dd260660a7e7f77f32b7e4c993fd9c23d3c1", url = "https://s3.eu-central-1.amazonaws.com/eth-pkg.com/backup/bookworm/20250107/aspnetcore-runtime-9.0_9.0.0-1_amd64.deb" },
    { name = "aspnetcore-targeting-pack-9.0_9.0.0-1_amd64", hash = "4038bdc5a54178fe2bfc329680906a14d43b282e", url = "https://s3.eu-central-1.amazonaws.com/eth-pkg.com/backup/bookworm/20250107/aspnetcore-targeting-pack-9.0_9.0.0-1_amd64.deb" },
    { name = "dotnet-apphost-pack-9.0_9.0.0-1_amd64", hash = "03e19d0580ab4114c64ef12d0c02a4f13f0da717", url = "https://s3.eu-central-1.amazonaws.com/eth-pkg.com/backup/bookworm/20250107/dotnet-apphost-pack-9.0_9.0.0-1_amd64.deb" },
    { name = "dotnet-hostfxr-9.0_9.0.0-1_amd64", hash = "4b677d008ac0135168bb49074135e213c7d335ac", url = "https://s3.eu-central-1.amazonaws.com/eth-pkg.com/backup/bookworm/20250107/dotnet-hostfxr-9.0_9.0.0-1_amd64.deb" },
    { name = "dotnet-runtime-9.0_9.0.0-1_amd64", hash = "5ed8ce77eecf489180ab7e366d868e443f2900b4", url = "https://s3.eu-central-1.amazonaws.com/eth-pkg.com/backup/bookworm/20250107/dotnet-runtime-9.0_9.0.0-1_amd64.deb" },
    { name = "dotnet-sdk-9.0_9.0.101-1_amd64", hash = "e97ce6be21ad8d7401ca45829c708b5c9e2532f0", url = "https://s3.eu-central-1.amazonaws.com/eth-pkg.com/backup/bookworm/20250107/dotnet-sdk-9.0_9.0.101-1_amd64.deb" },
    { name = "dotnet-targeting-pack-9.0_9.0.0-1_amd64", hash = "cb3967451b497e72ea773a2db1be15b862dd0b0b", url = "https://s3.eu-central-1.amazonaws.com/eth-pkg.com/backup/bookworm/20250107/dotnet-targeting-pack-9.0_9.0.0-1_amd64.deb" },
    { name = "netstandard-targeting-pack-2.1_2.1.0-1_amd64", hash = "c849f17d5e8cdce4b068e2897939be7de4b839d3", url = "https://s3.eu-central-1.amazonaws.com/eth-pkg.com/backup/bookworm/20250107/netstandard-targeting-pack-2.1_2.1.0-1_amd64.deb" },
]

use_backup_version = false

[build_env]
codename = "bookworm"
arch = "amd64"
pkg_builder_version = "0.2.9"
debcrafter_version = "2711b53"
run_lintian = true
run_piuparts = true
run_autopkgtest = true
lintian_version = "2.116.3"
piuparts_version = "1.1.7"
autopkgtest_version = "5.28"
sbuild_version = "0.85.6"
# package directory
workdir = "~/.pkg-builder/packages/bookworm"
language_env = "dotnet"
