[package_fields]
spec_file = "eth-node-nimbus-eth2.sss"
package_name = "eth-node-nimbus-eth2"
version_number = "25.3.0"
revision_number = "1"
homepage="https://github.com/status-im/nimbus-eth2"

[package_type]
# virtual | git | default
package_type="git"
git_url="https://github.com/status-im/nimbus-eth2.git"
git_tag="v25.3.0"
submodules = [
        { "commit" = "73fbb29019c19887235c1da456cfbfd5b4835184", "path" = "vendor/EIPs" },
        { "commit" = "7721c955b522f4893265bb36a6de4f8edef8b54b", "path" = "vendor/NimYAML" },
        { "commit" = "3f44fafa888439f56fc60d2f6173bfe63f31c962", "path" = "vendor/gnosis-chain-configs" },
        { "commit" = "34d0a04577b36dcf5ba304a2ba8222c8f1f4e639", "path" = "vendor/holesky" },
        { "commit" = "dd91689396a9824ed3c78d0576cf5d854504c25c", "path" = "vendor/mainnet" },
        { "commit" = "c7683c5a6221605bbab31b53d01feb3a3161bb8b", "path" = "vendor/nim-bearssl" },
        { "commit" = "52ae4332c749d89fa05226f5493decae568f682c", "path" = "vendor/nim-blscurve" },
        { "commit" = "81a4a7a360c78be9c80c8f735c76b6d4a1517304", "path" = "vendor/nim-chronicles" },
        { "commit" = "c04576d829b8a0a1b12baaa8bc92037501b3a4a0", "path" = "vendor/nim-chronos" },
        { "commit" = "e214b3992a31acece6a9aada7d0a1ad37c928f3b", "path" = "vendor/nim-confutils" },
        { "commit" = "e973d0b8ef0d49ec8094f88d606174c862cc964c", "path" = "vendor/nim-eth" },
        { "commit" = "d84994bdbc5ec7d79ad3e4c71c637941710d04af", "path" = "vendor/nim-eth2-scenarios" },
        { "commit" = "2b08c774afaafd600cf4c6f994cf78b8aa090c0c", "path" = "vendor/nim-faststreams" },
        { "commit" = "79cbab1460f4c0cdde2084589d017c43a3d7b4f1", "path" = "vendor/nim-http-utils" },
        { "commit" = "274372132de497e6b7b793c9d5d5474b71bf80a2", "path" = "vendor/nim-json-rpc" },
        { "commit" = "6eadb6e939ffa7882ff5437033c11a9464d3385c", "path" = "vendor/nim-json-serialization" },
        { "commit" = "33d2e9a5d4df1bbf4aca7cf00457bf15b1d657a6", "path" = "vendor/nim-kzg4844" },
        { "commit" = "624d1f8719d9e34c5d0c1f15652168a1222e1782", "path" = "vendor/nim-libbacktrace" },
        { "commit" = "b0f83fd48c90224a30679f6079af60767c30f8e1", "path" = "vendor/nim-libp2p" },
        { "commit" = "25ffd054fd774f8cf7935e75d6cad542306d7802", "path" = "vendor/nim-metrics" },
        { "commit" = "c35304151ea39077330f225e3837450990d55e48", "path" = "vendor/nim-minilru" },
        { "commit" = "213ac13dfe5c4830474912c48181b86b73f1ec1f", "path" = "vendor/nim-nat-traversal" },
        { "commit" = "08caa2a4da40580ed7fe3ce723b3f7feabcca8e5", "path" = "vendor/nim-normalize" },
        { "commit" = "92b1c7ff141e6920e1f8a98a14c35c1fa098e3be", "path" = "vendor/nim-presto" },
        { "commit" = "71d404b314479a6205bfd050f4fe5fe49cdafc69", "path" = "vendor/nim-results" },
        { "commit" = "62e16b4dff513f1eea7148a8cbba8a8c547b9546", "path" = "vendor/nim-secp256k1" },
        { "commit" = "2086c99608b4bf472e1ef5fe063710f280243396", "path" = "vendor/nim-serialization" },
        { "commit" = "9658ee0684fde6cd5fb904936a774ef82bd33344", "path" = "vendor/nim-snappy" },
        { "commit" = "cc4fefd538aa43814c5864c540fb75b567c2dcc3", "path" = "vendor/nim-sqlite3-abi" },
        { "commit" = "d7552018fe2fe1ab1b74a68517caa085a2309622", "path" = "vendor/nim-ssz-serialization" },
        { "commit" = "79e4fa5a9d3374db17ed63622714d3e1094c7f34", "path" = "vendor/nim-stew" },
        { "commit" = "1a2c661e3f50ff696b0b6692fab0d7bb2abf10cc", "path" = "vendor/nim-stint" },
        { "commit" = "7b74a716a40249720fd7da428113147942b9642d", "path" = "vendor/nim-taskpools" },
        { "commit" = "94d68e796c045d5b37cabc6be32d7bfa168f8857", "path" = "vendor/nim-testutils" },
        { "commit" = "fea85b27f0badcf617033ca1bc05444b5fd8aa7a", "path" = "vendor/nim-toml-serialization" },
        { "commit" = "66f2458710dc641dd4640368f9483c8a0ec70561", "path" = "vendor/nim-unicodedb" },
        { "commit" = "845b6af28b9f68f02d320e03ad18eccccea7ddb9", "path" = "vendor/nim-unittest2" },
        { "commit" = "a3bc5ad48e2b05fa253ba68bbd5b84e4ea234f50", "path" = "vendor/nim-web3" },
        { "commit" = "ebe308a79a7b440a11dfbe74f352be86a3883508", "path" = "vendor/nim-websock" },
        { "commit" = "3f7998095264d262a8d99e2be89045e6d9301537", "path" = "vendor/nim-zlib" },
        { "commit" = "d827fdc9968a4f06bba587dc38df2b20399f8cf5", "path" = "vendor/nim-zxcvbn" },
        { "commit" = "dff3634b5d843f9b63425086f1b13245e26b6177", "path" = "vendor/nimbus-benchmarking" },
        { "commit" = "4c6ff070c116450bb2c285691724ac9e6202cb28", "path" = "vendor/nimbus-build-system" },
        { "commit" = "ce9945b1b159d4c9b628f8c4cd2d262964692810", "path" = "vendor/nimbus-security-resources" },
        { "commit" = "dc07e3058c6904eef965394493b6ea99aa2adefc", "path" = "vendor/nimcrypto" },
        { "commit" = "f5e3652be045250fd2de1631683b110317592bd3", "path" = "vendor/sepolia" }
        ]



[package_type.language_env]
language_env = "nim"
nim_version = "2.0.6"
nim_binary_url = "https://nim-lang.org/download/nim-2.0.6-linux_x64.tar.xz"
nim_version_checksum = "4613c18f6c70d14f7fcbcb0c644425699862902ec64d7b785ededaf161815cdc nim-2.0.6-linux_x64.tar.xz"


[build_env]
codename="noble numbat"
arch = "amd64"
pkg_builder_version="0.2.11"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/noble"
