.PHONY: all

all:
    @$(MAKE) -f $(MAKEFILE)

ifeq ($(CLIENT), lighthouse)
    MAKEFILE := pkg_specs/eth-node-lighthouse/4.5.0/Makefile
else ifeq ($(CLIENT), erigon)
    MAKEFILE := pkg_specs/eth-node-erigon/4.5.0/Makefile
else
    $(error Invalid client. Please use 'make CLIENT=lighthouse' or 'make CLIENT=erigon')
endif

include $(MAKEFILE)

