#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which lighthouse)"
  assertEquals "/usr/bin/lighthouse" "$output"
}

test_invocation(){
  output="$(lighthouse --version)"
 # checked against https://github.com/sigp/lighthouse/releases/download/v4.5.0/lighthouse-v4.5.0-x86_64-unknown-linux-gnu.tar.gz
  assertContains "Lighthouse v4.5.0" "$output"
  assertContains "BLS library: blst-modern" "$output"
  assertContains "SHA256 hardware acceleration: true" "$output"
  assertContains "Allocator: jemalloc" "$output"
  assertContains "Profile: maxperf" "$output"
  assertContains "Specs: mainnet (true), minimal (false), gnosis (true)" "$output"
}

. shunit2