[verify]
package_hash=[
    { hash="bca682c31c137e6c129a76fbdeb5501e0445ccf2", name= "eth-node-lodestar_1.23.1-1.dsc"},
    { hash="5e9efbee9e184375e16a40f6cdb2b60e2a2a0074", name= "eth-node-lodestar_1.23.1.orig.tar.gz"},
    { hash="0a97ccbf5cdeaf8bede2512de0fafc28ece8fda6", name= "eth-node-lodestar_1.23.1-1.debian.tar.xz"},
    { hash="74e1a9bdc751201f7bafea3a5bd68050bd6c84ba", name= "eth-node-lodestar_1.23.1-1_amd64.deb"},
]
