[package_fields]
spec_file = "eth-beacon-genesis.sss"
package_name = "eth-beacon-genesis"
version_number = "<CLIENT_VERSION>"
revision_number = "<CLIENT_REVISION>"
homepage = "https://github.com/ethpandaops/eth-beacon-genesis"

[package_type]
# virtual | git | default
package_type = "default"
tarball_url = "https://github.com/miguelmota/ethpandaops/eth-beacon-genesis/archive/refs/tags/v<CLIENT_VERSION>.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "<CLIENT_PACKAGE_HASH>"

[package_type.language_env]
language_env = "go"
go_version = "1.24.2"
go_binary_url = "https://go.dev/dl/go1.24.2.linux-amd64.tar.gz"
go_binary_checksum = "68097bd680839cbc9d464a0edce4f7c333975e27a90246890e9f1078c7e702ad"

[build_env]
codename = "noble numbat"
arch = "amd64"
pkg_builder_version = "<PKG_BUILDER_VERSION>"
debcrafter_version = "2711b53"
run_lintian = true
run_piuparts = true
run_autopkgtest = true
lintian_version = "2.116.3"
piuparts_version = "1.1.7"
autopkgtest_version = "5.28"
sbuild_version = "0.85.6"
# package directory
workdir = "~/.pkg-builder/packages/noble"
