#!/usr/bin/env bash

set -e

display_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --conf-file FILE, -e FILE   Path to .conf formatted configuration file."
    echo "  --help, -h                    Displays this help text and exits."
    echo "  --version, -v                 Displays the version and exits."
    exit 0
}

display_version() {
    local version=$(basename "$(dirname "$(realpath "$0")")")
    echo "$0 version $version"
    exit 0
}

CONFIG_FILES=()
HELP=false
VERSION=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
    --conf-file | -e)
        CONFIG_FILES+=("$2")
        shift 2
        ;;
    --help | -h)
        HELP=true
        shift
        ;;
    --version | -v)
        VERSION=true
        shift
        ;;
    *)
        echo "Error: Unknown option $1"
        display_help
        ;;
    esac
done

if [ "$HELP" = true ]; then
    display_help
fi

if [ "$VERSION" = true ]; then
    display_version
fi

if [[ ${#CONFIG_FILES[@]} -eq 0 ]]; then
    echo "Error: At least one --conf-file option is required"
    display_help
fi

for CONFIG_FILE in "${CONFIG_FILES[@]}"; do
    if [[ -f "$CONFIG_FILE" ]]; then
        echo "Starting with configuration from $CONFIG_FILE"
        source "$CONFIG_FILE"
    else
        echo "Error: Configuration file $CONFIG_FILE not found."
        exit 1
    fi
done

OPTIONS=""

append_option() {
    local option=$1
    local value=$2
    if [ -n "$value" ]; then
        OPTIONS="$OPTIONS $option $value"
    fi
}

append_option "--datadir" "$NETHERMIND_DATADIR"
append_option "--config" "$NETHERMIND_CONFIG"
append_option "--baseDbPath" "$NETHERMIND_BASE_DB_PATH"
append_option "--log" "$NETHERMIND_LOG"
append_option "--configsDirectory" "$NETHERMIND_CONFIGS_DIRECTORY"
append_option "--loggerConfigSource" "$NETHERMIND_LOGGER_CONFIG_SOURCE"
append_option "--pluginsDirectory" "$NETHERMIND_PLUGINS_DIRECTORY"
append_option "--Aura.AllowAuRaPrivateChains" "$NETHERMIND_AURA_ALLOW_AURA_PRIVATE_CHAINS"
append_option "--Aura.ForceSealing" "$NETHERMIND_AURA_FORCE_SEALING"
append_option "--Aura.Minimum2MlnGasPerBlockWhenUsingBlockGasLimitContract" "$NETHERMIND_AURA_MINIMUM_2MLN_GAS_PER_BLOCK_WHEN_USING_BLOCK_GAS_LIMIT_CONTRACT"
append_option "--Aura.TxPriorityConfigFilePath" "$NETHERMIND_AURA_TX_PRIORITY_CONFIG_FILE_PATH"
append_option "--Aura.TxPriorityContractAddress" "$NETHERMIND_AURA_TX_PRIORITY_CONTRACT_ADDRESS"
append_option "--Blocks.BlockProductionTimeoutMs" "$NETHERMIND_BLOCKS_BLOCK_PRODUCTION_TIMEOUT_MS"
append_option "--Blocks.ExtraData" "$NETHERMIND_BLOCKS_EXTRA_DATA"
append_option "--Blocks.GenesisTimeoutMs" "$NETHERMIND_BLOCKS_GENESIS_TIMEOUT_MS"
append_option "--Blocks.MinGasPrice" "$NETHERMIND_BLOCKS_MIN_GAS_PRICE"
append_option "--Blocks.PreWarmStateOnBlockProcessing" "$NETHERMIND_BLOCKS_PRE_WARM_STATE_ON_BLOCK_PROCESSING"
append_option "--Blocks.RandomizedBlocks" "$NETHERMIND_BLOCKS_RANDOMIZED_BLOCKS"
append_option "--Blocks.SecondsPerSlot" "$NETHERMIND_BLOCKS_SECONDS_PER_SLOT"
append_option "--Blocks.TargetBlockGasLimit" "$NETHERMIND_BLOCKS_TARGET_BLOCK_GAS_LIMIT"
append_option "--Bloom.Index" "$NETHERMIND_BLOOM_INDEX"
append_option "--Bloom.IndexLevelBucketSizes" "$NETHERMIND_BLOOM_INDEX_LEVEL_BUCKET_SIZES"
append_option "--Bloom.Migration" "$NETHERMIND_BLOOM_MIGRATION"
append_option "--Bloom.MigrationStatistics" "$NETHERMIND_BLOOM_MIGRATION_STATISTICS"
append_option "--CensorshipDetector.AddressesForCensorshipDetection" "$NETHERMIND_CENSORSHIP_DETECTOR_ADDRESSES_FOR_CENSORSHIP_DETECTION"
append_option "--CensorshipDetector.BlockCensorshipThreshold" "$NETHERMIND_CENSORSHIP_DETECTOR_BLOCK_CENSORSHIP_THRESHOLD"
append_option "--CensorshipDetector.Enabled" "$NETHERMIND_CENSORSHIP_DETECTOR_ENABLED"
append_option "--Db.AdditionalRocksDbOptions" "$NETHERMIND_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.AdviseRandomOnOpen" "$NETHERMIND_DB_ADVISE_RANDOM_ON_OPEN"
append_option "--Db.AllowMmapReads" "$NETHERMIND_DB_ALLOW_MMAP_READS"
append_option "--Db.BlobTransactionsDbBlockCacheSize" "$NETHERMIND_DB_BLOB_TRANSACTIONS_DB_BLOCK_CACHE_SIZE"
append_option "--Db.BlockCacheSize" "$NETHERMIND_DB_BLOCK_CACHE_SIZE"
append_option "--Db.BlockInfosDbAdditionalRocksDbOptions" "$NETHERMIND_DB_BLOCK_INFOS_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.BlockInfosDbBlockCacheSize" "$NETHERMIND_DB_BLOCK_INFOS_DB_BLOCK_CACHE_SIZE"
append_option "--Db.BlockInfosDbBlockSize" "$NETHERMIND_DB_BLOCK_INFOS_DB_BLOCK_SIZE"
append_option "--Db.BlockInfosDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_BLOCK_INFOS_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.BlockInfosDbCompactionReadAhead" "$NETHERMIND_DB_BLOCK_INFOS_DB_COMPACTION_READ_AHEAD"
append_option "--Db.BlockInfosDbMaxBytesPerSec" "$NETHERMIND_DB_BLOCK_INFOS_DB_MAX_BYTES_PER_SEC"
append_option "--Db.BlockInfosDbMaxOpenFiles" "$NETHERMIND_DB_BLOCK_INFOS_DB_MAX_OPEN_FILES"
append_option "--Db.BlockInfosDbUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_BLOCK_INFOS_DB_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.BlockInfosDbUseDirectReads" "$NETHERMIND_DB_BLOCK_INFOS_DB_USE_DIRECT_READS"
append_option "--Db.BlockInfosDbWriteBufferNumber" "$NETHERMIND_DB_BLOCK_INFOS_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.BlockInfosDbWriteBufferSize" "$NETHERMIND_DB_BLOCK_INFOS_DB_WRITE_BUFFER_SIZE"
append_option "--Db.BlockNumbersDbAdditionalRocksDbOptions" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.BlockNumbersDbBlockCacheSize" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_BLOCK_CACHE_SIZE"
append_option "--Db.BlockNumbersDbBlockSize" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_BLOCK_SIZE"
append_option "--Db.BlockNumbersDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.BlockNumbersDbCompactionReadAhead" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_COMPACTION_READ_AHEAD"
append_option "--Db.BlockNumbersDbMaxBytesForLevelBase" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_MAX_BYTES_FOR_LEVEL_BASE"
append_option "--Db.BlockNumbersDbMaxBytesPerSec" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_MAX_BYTES_PER_SEC"
append_option "--Db.BlockNumbersDbMaxOpenFiles" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_MAX_OPEN_FILES"
append_option "--Db.BlockNumbersDbRowCacheSize" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_ROW_CACHE_SIZE"
append_option "--Db.BlockNumbersDbUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.BlockNumbersDbUseDirectReads" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_USE_DIRECT_READS"
append_option "--Db.BlockNumbersDbUseHashIndex" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_USE_HASH_INDEX"
append_option "--Db.BlockNumbersDbUseHashSkipListMemtable" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_USE_HASH_SKIP_LIST_MEMTABLE"
append_option "--Db.BlockNumbersDbWriteBufferNumber" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.BlockNumbersDbWriteBufferSize" "$NETHERMIND_DB_BLOCK_NUMBERS_DB_WRITE_BUFFER_SIZE"
append_option "--Db.BlockRestartInterval" "$NETHERMIND_DB_BLOCK_RESTART_INTERVAL"
append_option "--Db.BlockSize" "$NETHERMIND_DB_BLOCK_SIZE"
append_option "--Db.BlocksBlockSize" "$NETHERMIND_DB_BLOCKS_BLOCK_SIZE"
append_option "--Db.BlocksDbAdditionalRocksDbOptions" "$NETHERMIND_DB_BLOCKS_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.BlocksDbBlockCacheSize" "$NETHERMIND_DB_BLOCKS_DB_BLOCK_CACHE_SIZE"
append_option "--Db.BlocksDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_BLOCKS_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.BlocksDbCompactionReadAhead" "$NETHERMIND_DB_BLOCKS_DB_COMPACTION_READ_AHEAD"
append_option "--Db.BlocksDbMaxBytesPerSec" "$NETHERMIND_DB_BLOCKS_DB_MAX_BYTES_PER_SEC"
append_option "--Db.BlocksDbMaxOpenFiles" "$NETHERMIND_DB_BLOCKS_DB_MAX_OPEN_FILES"
append_option "--Db.BlocksDbUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_BLOCKS_DB_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.BlocksDbUseDirectReads" "$NETHERMIND_DB_BLOCKS_DB_USE_DIRECT_READS"
append_option "--Db.BlocksDbWriteBufferNumber" "$NETHERMIND_DB_BLOCKS_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.BlocksDbWriteBufferSize" "$NETHERMIND_DB_BLOCKS_DB_WRITE_BUFFER_SIZE"
append_option "--Db.BloomDbAdditionalRocksDbOptions" "$NETHERMIND_DB_BLOOM_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.BloomDbBlockCacheSize" "$NETHERMIND_DB_BLOOM_DB_BLOCK_CACHE_SIZE"
append_option "--Db.BloomDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_BLOOM_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.BloomDbMaxBytesPerSec" "$NETHERMIND_DB_BLOOM_DB_MAX_BYTES_PER_SEC"
append_option "--Db.BloomDbMaxOpenFiles" "$NETHERMIND_DB_BLOOM_DB_MAX_OPEN_FILES"
append_option "--Db.BloomDbWriteBufferNumber" "$NETHERMIND_DB_BLOOM_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.BloomDbWriteBufferSize" "$NETHERMIND_DB_BLOOM_DB_WRITE_BUFFER_SIZE"
append_option "--Db.BloomFilterBitsPerKey" "$NETHERMIND_DB_BLOOM_FILTER_BITS_PER_KEY"
append_option "--Db.BytesPerSync" "$NETHERMIND_DB_BYTES_PER_SYNC"
append_option "--Db.CacheIndexAndFilterBlocks" "$NETHERMIND_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.CodeCompactionReadAhead" "$NETHERMIND_DB_CODE_COMPACTION_READ_AHEAD"
append_option "--Db.CodeDbAdditionalRocksDbOptions" "$NETHERMIND_DB_CODE_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.CodeDbBlockCacheSize" "$NETHERMIND_DB_CODE_DB_BLOCK_CACHE_SIZE"
append_option "--Db.CodeDbBlockSize" "$NETHERMIND_DB_CODE_DB_BLOCK_SIZE"
append_option "--Db.CodeDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_CODE_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.CodeDbMaxBytesPerSec" "$NETHERMIND_DB_CODE_DB_MAX_BYTES_PER_SEC"
append_option "--Db.CodeDbMaxOpenFiles" "$NETHERMIND_DB_CODE_DB_MAX_OPEN_FILES"
append_option "--Db.CodeDbRowCacheSize" "$NETHERMIND_DB_CODE_DB_ROW_CACHE_SIZE"
append_option "--Db.CodeDbUseHashIndex" "$NETHERMIND_DB_CODE_DB_USE_HASH_INDEX"
append_option "--Db.CodeDbUseHashSkipListMemtable" "$NETHERMIND_DB_CODE_DB_USE_HASH_SKIP_LIST_MEMTABLE"
append_option "--Db.CodeDbWriteBufferNumber" "$NETHERMIND_DB_CODE_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.CodeDbWriteBufferSize" "$NETHERMIND_DB_CODE_DB_WRITE_BUFFER_SIZE"
append_option "--Db.CodeUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_CODE_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.CodeUseDirectReads" "$NETHERMIND_DB_CODE_USE_DIRECT_READS"
append_option "--Db.CompactionReadAhead" "$NETHERMIND_DB_COMPACTION_READ_AHEAD"
append_option "--Db.CompressibilityHint" "$NETHERMIND_DB_COMPRESSIBILITY_HINT"
append_option "--Db.DataBlockIndexUtilRatio" "$NETHERMIND_DB_DATA_BLOCK_INDEX_UTIL_RATIO"
append_option "--Db.DisableCompression" "$NETHERMIND_DB_DISABLE_COMPRESSION"
append_option "--Db.EnableDbStatistics" "$NETHERMIND_DB_ENABLE_DB_STATISTICS"
append_option "--Db.EnableFileWarmer" "$NETHERMIND_DB_ENABLE_FILE_WARMER"
append_option "--Db.EnableMetricsUpdater" "$NETHERMIND_DB_ENABLE_METRICS_UPDATER"
append_option "--Db.HeadersDbAdditionalRocksDbOptions" "$NETHERMIND_DB_HEADERS_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.HeadersDbBlockCacheSize" "$NETHERMIND_DB_HEADERS_DB_BLOCK_CACHE_SIZE"
append_option "--Db.HeadersDbBlockSize" "$NETHERMIND_DB_HEADERS_DB_BLOCK_SIZE"
append_option "--Db.HeadersDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_HEADERS_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.HeadersDbCompactionReadAhead" "$NETHERMIND_DB_HEADERS_DB_COMPACTION_READ_AHEAD"
append_option "--Db.HeadersDbMaxBytesForLevelBase" "$NETHERMIND_DB_HEADERS_DB_MAX_BYTES_FOR_LEVEL_BASE"
append_option "--Db.HeadersDbMaxBytesPerSec" "$NETHERMIND_DB_HEADERS_DB_MAX_BYTES_PER_SEC"
append_option "--Db.HeadersDbMaxOpenFiles" "$NETHERMIND_DB_HEADERS_DB_MAX_OPEN_FILES"
append_option "--Db.HeadersDbUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_HEADERS_DB_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.HeadersDbUseDirectReads" "$NETHERMIND_DB_HEADERS_DB_USE_DIRECT_READS"
append_option "--Db.HeadersDbWriteBufferNumber" "$NETHERMIND_DB_HEADERS_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.HeadersDbWriteBufferSize" "$NETHERMIND_DB_HEADERS_DB_WRITE_BUFFER_SIZE"
append_option "--Db.LevelCompactionDynamicLevelBytes" "$NETHERMIND_DB_LEVEL_COMPACTION_DYNAMIC_LEVEL_BYTES"
append_option "--Db.MaxBytesForLevelBase" "$NETHERMIND_DB_MAX_BYTES_FOR_LEVEL_BASE"
append_option "--Db.MaxBytesForLevelMultiplier" "$NETHERMIND_DB_MAX_BYTES_FOR_LEVEL_MULTIPLIER"
append_option "--Db.MaxBytesPerSec" "$NETHERMIND_DB_MAX_BYTES_PER_SEC"
append_option "--Db.MaxCompactionBytes" "$NETHERMIND_DB_MAX_COMPACTION_BYTES"
append_option "--Db.MaxOpenFiles" "$NETHERMIND_DB_MAX_OPEN_FILES"
append_option "--Db.MaxWriteBufferSizeToMaintain" "$NETHERMIND_DB_MAX_WRITE_BUFFER_SIZE_TO_MAINTAIN"
append_option "--Db.MemtablePrefixBloomSizeRatio" "$NETHERMIND_DB_MEMTABLE_PREFIX_BLOOM_SIZE_RATIO"
append_option "--Db.MetadataCompactionReadAhead" "$NETHERMIND_DB_METADATA_COMPACTION_READ_AHEAD"
append_option "--Db.MetadataDbAdditionalRocksDbOptions" "$NETHERMIND_DB_METADATA_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.MetadataDbBlockCacheSize" "$NETHERMIND_DB_METADATA_DB_BLOCK_CACHE_SIZE"
append_option "--Db.MetadataDbBlockSize" "$NETHERMIND_DB_METADATA_DB_BLOCK_SIZE"
append_option "--Db.MetadataDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_METADATA_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.MetadataDbMaxBytesPerSec" "$NETHERMIND_DB_METADATA_DB_MAX_BYTES_PER_SEC"
append_option "--Db.MetadataDbMaxOpenFiles" "$NETHERMIND_DB_METADATA_DB_MAX_OPEN_FILES"
append_option "--Db.MetadataDbWriteBufferNumber" "$NETHERMIND_DB_METADATA_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.MetadataDbWriteBufferSize" "$NETHERMIND_DB_METADATA_DB_WRITE_BUFFER_SIZE"
append_option "--Db.MetadataUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_METADATA_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.MetadataUseDirectReads" "$NETHERMIND_DB_METADATA_USE_DIRECT_READS"
append_option "--Db.MinWriteBufferNumberToMerge" "$NETHERMIND_DB_MIN_WRITE_BUFFER_NUMBER_TO_MERGE"
append_option "--Db.OnlyCompressLastLevel" "$NETHERMIND_DB_ONLY_COMPRESS_LAST_LEVEL"
append_option "--Db.OptimizeFiltersForHits" "$NETHERMIND_DB_OPTIMIZE_FILTERS_FOR_HITS"
append_option "--Db.PendingTxsDbAdditionalRocksDbOptions" "$NETHERMIND_DB_PENDING_TXS_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.PendingTxsDbBlockCacheSize" "$NETHERMIND_DB_PENDING_TXS_DB_BLOCK_CACHE_SIZE"
append_option "--Db.PendingTxsDbBlockSize" "$NETHERMIND_DB_PENDING_TXS_DB_BLOCK_SIZE"
append_option "--Db.PendingTxsDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_PENDING_TXS_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.PendingTxsDbCompactionReadAhead" "$NETHERMIND_DB_PENDING_TXS_DB_COMPACTION_READ_AHEAD"
append_option "--Db.PendingTxsDbMaxBytesPerSec" "$NETHERMIND_DB_PENDING_TXS_DB_MAX_BYTES_PER_SEC"
append_option "--Db.PendingTxsDbMaxOpenFiles" "$NETHERMIND_DB_PENDING_TXS_DB_MAX_OPEN_FILES"
append_option "--Db.PendingTxsDbUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_PENDING_TXS_DB_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.PendingTxsDbUseDirectReads" "$NETHERMIND_DB_PENDING_TXS_DB_USE_DIRECT_READS"
append_option "--Db.PendingTxsDbWriteBufferNumber" "$NETHERMIND_DB_PENDING_TXS_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.PendingTxsDbWriteBufferSize" "$NETHERMIND_DB_PENDING_TXS_DB_WRITE_BUFFER_SIZE"
append_option "--Db.PrefixExtractorLength" "$NETHERMIND_DB_PREFIX_EXTRACTOR_LENGTH"
append_option "--Db.ReadAheadSize" "$NETHERMIND_DB_READ_AHEAD_SIZE"
append_option "--Db.ReceiptsDbAdditionalRocksDbOptions" "$NETHERMIND_DB_RECEIPTS_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.ReceiptsDbBlockCacheSize" "$NETHERMIND_DB_RECEIPTS_DB_BLOCK_CACHE_SIZE"
append_option "--Db.ReceiptsDbBlockSize" "$NETHERMIND_DB_RECEIPTS_DB_BLOCK_SIZE"
append_option "--Db.ReceiptsDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_RECEIPTS_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.ReceiptsDbCompactionReadAhead" "$NETHERMIND_DB_RECEIPTS_DB_COMPACTION_READ_AHEAD"
append_option "--Db.ReceiptsDbCompressibilityHint" "$NETHERMIND_DB_RECEIPTS_DB_COMPRESSIBILITY_HINT"
append_option "--Db.ReceiptsDbMaxBytesPerSec" "$NETHERMIND_DB_RECEIPTS_DB_MAX_BYTES_PER_SEC"
append_option "--Db.ReceiptsDbMaxOpenFiles" "$NETHERMIND_DB_RECEIPTS_DB_MAX_OPEN_FILES"
append_option "--Db.ReceiptsDbTargetFileSizeBase" "$NETHERMIND_DB_RECEIPTS_DB_TARGET_FILE_SIZE_BASE"
append_option "--Db.ReceiptsDbUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_RECEIPTS_DB_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.ReceiptsDbUseDirectReads" "$NETHERMIND_DB_RECEIPTS_DB_USE_DIRECT_READS"
append_option "--Db.ReceiptsDbWriteBufferNumber" "$NETHERMIND_DB_RECEIPTS_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.ReceiptsDbWriteBufferSize" "$NETHERMIND_DB_RECEIPTS_DB_WRITE_BUFFER_SIZE"
append_option "--Db.RecycleLogFileNum" "$NETHERMIND_DB_RECYCLE_LOG_FILE_NUM"
append_option "--Db.RowCacheSize" "$NETHERMIND_DB_ROW_CACHE_SIZE"
append_option "--Db.SharedBlockCacheSize" "$NETHERMIND_DB_SHARED_BLOCK_CACHE_SIZE"
append_option "--Db.SkipMemoryHintSetting" "$NETHERMIND_DB_SKIP_MEMORY_HINT_SETTING"
append_option "--Db.StateDbAdditionalRocksDbOptions" "$NETHERMIND_DB_STATE_DB_ADDITIONAL_ROCKS_DB_OPTIONS"
append_option "--Db.StateDbAdviseRandomOnOpen" "$NETHERMIND_DB_STATE_DB_ADVISE_RANDOM_ON_OPEN"
append_option "--Db.StateDbAllowMmapReads" "$NETHERMIND_DB_STATE_DB_ALLOW_MMAP_READS"
append_option "--Db.StateDbBlockCacheSize" "$NETHERMIND_DB_STATE_DB_BLOCK_CACHE_SIZE"
append_option "--Db.StateDbBlockRestartInterval" "$NETHERMIND_DB_STATE_DB_BLOCK_RESTART_INTERVAL"
append_option "--Db.StateDbBlockSize" "$NETHERMIND_DB_STATE_DB_BLOCK_SIZE"
append_option "--Db.StateDbBloomFilterBitsPerKey" "$NETHERMIND_DB_STATE_DB_BLOOM_FILTER_BITS_PER_KEY"
append_option "--Db.StateDbCacheIndexAndFilterBlocks" "$NETHERMIND_DB_STATE_DB_CACHE_INDEX_AND_FILTER_BLOCKS"
append_option "--Db.StateDbCompactionReadAhead" "$NETHERMIND_DB_STATE_DB_COMPACTION_READ_AHEAD"
append_option "--Db.StateDbCompressibilityHint" "$NETHERMIND_DB_STATE_DB_COMPRESSIBILITY_HINT"
append_option "--Db.StateDbDataBlockIndexUtilRatio" "$NETHERMIND_DB_STATE_DB_DATA_BLOCK_INDEX_UTIL_RATIO"
append_option "--Db.StateDbDisableCompression" "$NETHERMIND_DB_STATE_DB_DISABLE_COMPRESSION"
append_option "--Db.StateDbEnableFileWarmer" "$NETHERMIND_DB_STATE_DB_ENABLE_FILE_WARMER"
append_option "--Db.StateDbMaxBytesForLevelBase" "$NETHERMIND_DB_STATE_DB_MAX_BYTES_FOR_LEVEL_BASE"
append_option "--Db.StateDbMaxBytesForLevelMultiplier" "$NETHERMIND_DB_STATE_DB_MAX_BYTES_FOR_LEVEL_MULTIPLIER"
append_option "--Db.StateDbMaxBytesPerSec" "$NETHERMIND_DB_STATE_DB_MAX_BYTES_PER_SEC"
append_option "--Db.StateDbMaxCompactionBytes" "$NETHERMIND_DB_STATE_DB_MAX_COMPACTION_BYTES"
append_option "--Db.StateDbMaxOpenFiles" "$NETHERMIND_DB_STATE_DB_MAX_OPEN_FILES"
append_option "--Db.StateDbMaxWriteBufferSizeToMaintain" "$NETHERMIND_DB_STATE_DB_MAX_WRITE_BUFFER_SIZE_TO_MAINTAIN"
append_option "--Db.StateDbMemtablePrefixBloomSizeRatio" "$NETHERMIND_DB_STATE_DB_MEMTABLE_PREFIX_BLOOM_SIZE_RATIO"
append_option "--Db.StateDbMinWriteBufferNumberToMerge" "$NETHERMIND_DB_STATE_DB_MIN_WRITE_BUFFER_NUMBER_TO_MERGE"
append_option "--Db.StateDbOnlyCompressLastLevel" "$NETHERMIND_DB_STATE_DB_ONLY_COMPRESS_LAST_LEVEL"
append_option "--Db.StateDbOptimizeFiltersForHits" "$NETHERMIND_DB_STATE_DB_OPTIMIZE_FILTERS_FOR_HITS"
append_option "--Db.StateDbPrefixExtractorLength" "$NETHERMIND_DB_STATE_DB_PREFIX_EXTRACTOR_LENGTH"
append_option "--Db.StateDbRowCacheSize" "$NETHERMIND_DB_STATE_DB_ROW_CACHE_SIZE"
append_option "--Db.StateDbTargetFileSizeMultiplier" "$NETHERMIND_DB_STATE_DB_TARGET_FILE_SIZE_MULTIPLIER"
append_option "--Db.StateDbUseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_STATE_DB_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.StateDbUseDirectReads" "$NETHERMIND_DB_STATE_DB_USE_DIRECT_READS"
append_option "--Db.StateDbUseHashIndex" "$NETHERMIND_DB_STATE_DB_USE_HASH_INDEX"
append_option "--Db.StateDbUseHashSkipListMemtable" "$NETHERMIND_DB_STATE_DB_USE_HASH_SKIP_LIST_MEMTABLE"
append_option "--Db.StateDbUseLz4" "$NETHERMIND_DB_STATE_DB_USE_LZ4"
append_option "--Db.StateDbUseRibbonFilterStartingFromLevel" "$NETHERMIND_DB_STATE_DB_USE_RIBBON_FILTER_STARTING_FROM_LEVEL"
append_option "--Db.StateDbUseTwoLevelIndex" "$NETHERMIND_DB_STATE_DB_USE_TWO_LEVEL_INDEX"
append_option "--Db.StateDbVerifyChecksum" "$NETHERMIND_DB_STATE_DB_VERIFY_CHECKSUM"
append_option "--Db.StateDbWriteBufferNumber" "$NETHERMIND_DB_STATE_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.StateDbWriteBufferSize" "$NETHERMIND_DB_STATE_DB_WRITE_BUFFER_SIZE"
append_option "--Db.StatsDumpPeriodSec" "$NETHERMIND_DB_STATS_DUMP_PERIOD_SEC"
append_option "--Db.TargetFileSizeBase" "$NETHERMIND_DB_TARGET_FILE_SIZE_BASE"
append_option "--Db.TargetFileSizeMultiplier" "$NETHERMIND_DB_TARGET_FILE_SIZE_MULTIPLIER"
append_option "--Db.UseDirectIoForFlushAndCompactions" "$NETHERMIND_DB_USE_DIRECT_IO_FOR_FLUSH_AND_COMPACTIONS"
append_option "--Db.UseDirectReads" "$NETHERMIND_DB_USE_DIRECT_READS"
append_option "--Db.UseHashIndex" "$NETHERMIND_DB_USE_HASH_INDEX"
append_option "--Db.UseHashSkipListMemtable" "$NETHERMIND_DB_USE_HASH_SKIP_LIST_MEMTABLE"
append_option "--Db.UseLz4" "$NETHERMIND_DB_USE_LZ4"
append_option "--Db.UseRibbonFilterStartingFromLevel" "$NETHERMIND_DB_USE_RIBBON_FILTER_STARTING_FROM_LEVEL"
append_option "--Db.UseTwoLevelIndex" "$NETHERMIND_DB_USE_TWO_LEVEL_INDEX"
append_option "--Db.VerifyChecksum" "$NETHERMIND_DB_VERIFY_CHECKSUM"
append_option "--Db.WriteAheadLogSync" "$NETHERMIND_DB_WRITE_AHEAD_LOG_SYNC"
append_option "--Db.WriteBufferNumber" "$NETHERMIND_DB_WRITE_BUFFER_NUMBER"
append_option "--Db.WriteBufferSize" "$NETHERMIND_DB_WRITE_BUFFER_SIZE"
append_option "--Discovery.BootnodePongTimeout" "$NETHERMIND_DISCOVERY_BOOTNODE_PONG_TIMEOUT"
append_option "--Discovery.Bootnodes" "$NETHERMIND_DISCOVERY_BOOTNODES"
append_option "--Discovery.BucketSize" "$NETHERMIND_DISCOVERY_BUCKET_SIZE"
append_option "--Discovery.Concurrency" "$NETHERMIND_DISCOVERY_CONCURRENCY"
append_option "--Discovery.DiscoveryInterval" "$NETHERMIND_DISCOVERY_DISCOVERY_INTERVAL"
append_option "--Discovery.DiscoveryNewCycleWaitTime" "$NETHERMIND_DISCOVERY_DISCOVERY_NEW_CYCLE_WAIT_TIME"
append_option "--Discovery.DiscoveryPersistenceInterval" "$NETHERMIND_DISCOVERY_DISCOVERY_PERSISTENCE_INTERVAL"
append_option "--Discovery.DiscoveryVersion" "$NETHERMIND_DISCOVERY_DISCOVERY_VERSION"
append_option "--Discovery.DropFullBucketNodeProbability" "$NETHERMIND_DISCOVERY_DROP_FULL_BUCKET_NODE_PROBABILITY"
append_option "--Discovery.EvictionCheckInterval" "$NETHERMIND_DISCOVERY_EVICTION_CHECK_INTERVAL"
append_option "--Discovery.MaxDiscoveryRounds" "$NETHERMIND_DISCOVERY_MAX_DISCOVERY_ROUNDS"
append_option "--Discovery.MaxNodeLifecycleManagersCount" "$NETHERMIND_DISCOVERY_MAX_NODE_LIFECYCLE_MANAGERS_COUNT"
append_option "--Discovery.MaxOutgoingMessagePerSecond" "$NETHERMIND_DISCOVERY_MAX_OUTGOING_MESSAGE_PER_SECOND"
append_option "--Discovery.NodeLifecycleManagersCleanupCount" "$NETHERMIND_DISCOVERY_NODE_LIFECYCLE_MANAGERS_CLEANUP_COUNT"
append_option "--Discovery.PingRetryCount" "$NETHERMIND_DISCOVERY_PING_RETRY_COUNT"
append_option "--Discovery.PongTimeout" "$NETHERMIND_DISCOVERY_PONG_TIMEOUT"
append_option "--Discovery.SendNodeTimeout" "$NETHERMIND_DISCOVERY_SEND_NODE_TIMEOUT"
append_option "--Discovery.UdpChannelCloseTimeout" "$NETHERMIND_DISCOVERY_UDP_CHANNEL_CLOSE_TIMEOUT"
append_option "--EthStats.Contact" "$NETHERMIND_ETHSTATS_CONTACT"
append_option "--EthStats.Enabled" "$NETHERMIND_ETHSTATS_ENABLED"
append_option "--EthStats.Name" "$NETHERMIND_ETHSTATS_NAME"
append_option "--EthStats.Secret" "$NETHERMIND_ETHSTATS_SECRET"
append_option "--EthStats.SendInterval" "$NETHERMIND_ETHSTATS_SEND_INTERVAL"
append_option "--EthStats.Server" "$NETHERMIND_ETHSTATS_SERVER"
append_option "--HealthChecks.Enabled" "$NETHERMIND_HEALTHCHECKS_ENABLED"
append_option "--HealthChecks.LowStorageCheckAwaitOnStartup" "$NETHERMIND_HEALTHCHECKS_LOW_STORAGE_CHECK_AWAIT_ON_STARTUP"
append_option "--HealthChecks.LowStorageSpaceShutdownThreshold" "$NETHERMIND_HEALTHCHECKS_LOW_STORAGE_SPACE_SHUTDOWN_THRESHOLD"
append_option "--HealthChecks.LowStorageSpaceWarningThreshold" "$NETHERMIND_HEALTHCHECKS_LOW_STORAGE_SPACE_WARNING_THRESHOLD"
append_option "--HealthChecks.MaxIntervalClRequestTime" "$NETHERMIND_HEALTHCHECKS_MAX_INTERVAL_CL_REQUEST_TIME"
append_option "--HealthChecks.MaxIntervalWithoutProcessedBlock" "$NETHERMIND_HEALTHCHECKS_MAX_INTERVAL_WITHOUT_PROCESSED_BLOCK"
append_option "--HealthChecks.MaxIntervalWithoutProducedBlock" "$NETHERMIND_HEALTHCHECKS_MAX_INTERVAL_WITHOUT_PRODUCED_BLOCK"
append_option "--HealthChecks.PollingInterval" "$NETHERMIND_HEALTHCHECKS_POLLING_INTERVAL"
append_option "--HealthChecks.Slug" "$NETHERMIND_HEALTHCHECKS_SLUG"
append_option "--HealthChecks.UIEnabled" "$NETHERMIND_HEALTHCHECKS_UI_ENABLED"
append_option "--HealthChecks.WebhooksEnabled" "$NETHERMIND_HEALTHCHECKS_WEBHOOKS_ENABLED"
append_option "--HealthChecks.WebhooksPayload" "$NETHERMIND_HEALTHCHECKS_WEBHOOKS_PAYLOAD"
append_option "--HealthChecks.WebhooksRestorePayload" "$NETHERMIND_HEALTHCHECKS_WEBHOOKS_RESTORE_PAYLOAD"
append_option "--HealthChecks.WebhooksUri" "$NETHERMIND_HEALTHCHECKS_WEBHOOKS_URI"
append_option "--Hive.BlocksDir" "$NETHERMIND_HIVE_BLOCKS_DIR"
append_option "--Hive.ChainFile" "$NETHERMIND_HIVE_CHAIN_FILE"
append_option "--Hive.Enabled" "$NETHERMIND_HIVE_ENABLED"
append_option "--Hive.GenesisFilePath" "$NETHERMIND_HIVE_GENESIS_FILE_PATH"
append_option "--Hive.KeysDir" "$NETHERMIND_HIVE_KEYS_DIR"
append_option "--Init.AutoDump" "$NETHERMIND_INIT_AUTO_DUMP"
append_option "--Init.BackgroundTaskConcurrency" "$NETHERMIND_INIT_BACKGROUND_TASK_CONCURRENCY"
append_option "--Init.BadBlocksStored" "$NETHERMIND_INIT_BAD_BLOCKS_STORED"
append_option "--Init.BaseDbPath" "$NETHERMIND_INIT_BASE_DB_PATH"
append_option "--Init.ChainSpecPath" "$NETHERMIND_INIT_CHAIN_SPEC_PATH"
append_option "--Init.DiagnosticMode" "$NETHERMIND_INIT_DIAGNOSTIC_MODE"
append_option "--Init.DisableGcOnNewPayload" "$NETHERMIND_INIT_DISABLE_GC_ON_NEW_PAYLOAD"
append_option "--Init.DisableMallocOpts" "$NETHERMIND_INIT_DISABLE_MALLOC_OPTS"
append_option "--Init.DiscoveryEnabled" "$NETHERMIND_INIT_DISCOVERY_ENABLED"
append_option "--Init.EnableUnsecuredDevWallet" "$NETHERMIND_INIT_ENABLE_UNSECURED_DEV_WALLET"
append_option "--Init.ExitOnBlockNumber" "$NETHERMIND_INIT_EXIT_ON_BLOCK_NUMBER"
append_option "--Init.GenesisHash" "$NETHERMIND_INIT_GENESIS_HASH"
append_option "--Init.HiveChainSpecPath" "$NETHERMIND_INIT_HIVE_CHAIN_SPEC_PATH"
append_option "--Init.IsMining" "$NETHERMIND_INIT_IS_MINING"
append_option "--Init.KeepDevWalletInMemory" "$NETHERMIND_INIT_KEEP_DEV_WALLET_IN_MEMORY"
append_option "--Init.KzgSetupPath" "$NETHERMIND_INIT_KZG_SETUP_PATH"
append_option "--Init.LogDirectory" "$NETHERMIND_INIT_LOG_DIRECTORY"
append_option "--Init.LogFileName" "$NETHERMIND_INIT_LOG_FILE_NAME"
append_option "--Init.LogRules" "$NETHERMIND_INIT_LOG_RULES"
append_option "--Init.MemoryHint" "$NETHERMIND_INIT_MEMORY_HINT"
append_option "--Init.PeerManagerEnabled" "$NETHERMIND_INIT_PEER_MANAGER_ENABLED"
append_option "--Init.ProcessingEnabled" "$NETHERMIND_INIT_PROCESSING_ENABLED"
append_option "--Init.ReceiptsMigration" "$NETHERMIND_INIT_RECEIPTS_MIGRATION"
append_option "--Init.RpcDbUrl" "$NETHERMIND_INIT_RPC_DB_URL"
append_option "--Init.StateDbKeyScheme" "$NETHERMIND_INIT_STATE_DB_KEY_SCHEME"
append_option "--Init.StaticNodesPath" "$NETHERMIND_INIT_STATIC_NODES_PATH"
append_option "--Init.StoreReceipts" "$NETHERMIND_INIT_STORE_RECEIPTS"
append_option "--Init.WebSocketsEnabled" "$NETHERMIND_INIT_WEBSOCKETS_ENABLED"
append_option "--JsonRpc.AdditionalRpcUrls" "$NETHERMIND_JSONRPC_ADDITIONAL_RPC_URLS"
append_option "--JsonRpc.BufferResponses" "$NETHERMIND_JSONRPC_BUFFER_RESPONSES"
append_option "--JsonRpc.CallsFilterFilePath" "$NETHERMIND_JSONRPC_CALLS_FILTER_FILE_PATH"
append_option "--JsonRpc.Enabled" "$NETHERMIND_JSONRPC_ENABLED"
append_option "--JsonRpc.EnabledModules" "$NETHERMIND_JSONRPC_ENABLED_MODULES"
append_option "--JsonRpc.EngineEnabledModules" "$NETHERMIND_JSONRPC_ENGINE_ENABLED_MODULES"
append_option "--JsonRpc.EngineHost" "$NETHERMIND_JSONRPC_ENGINE_HOST"
append_option "--JsonRpc.EnginePort" "$NETHERMIND_JSONRPC_ENGINE_PORT"
append_option "--JsonRpc.EstimateErrorMargin" "$NETHERMIND_JSONRPC_ESTIMATE_ERROR_MARGIN"
append_option "--JsonRpc.EthModuleConcurrentInstances" "$NETHERMIND_JSONRPC_ETH_MODULE_CONCURRENT_INSTANCES"
append_option "--JsonRpc.GasCap" "$NETHERMIND_JSONRPC_GAS_CAP"
append_option "--JsonRpc.Host" "$NETHERMIND_JSONRPC_HOST"
append_option "--JsonRpc.IpcUnixDomainSocketPath" "$NETHERMIND_JSONRPC_IPC_UNIX_DOMAIN_SOCKET_PATH"
append_option "--JsonRpc.JwtSecretFile" "$NETHERMIND_JSONRPC_JWT_SECRET_FILE"
append_option "--JsonRpc.MaxBatchResponseBodySize" "$NETHERMIND_JSONRPC_MAX_BATCH_RESPONSE_BODY_SIZE"
append_option "--JsonRpc.MaxBatchSize" "$NETHERMIND_JSONRPC_MAX_BATCH_SIZE"
append_option "--JsonRpc.MaxLoggedRequestParametersCharacters" "$NETHERMIND_JSONRPC_MAX_LOGGED_REQUEST_PARAMETERS_CHARACTERS"
append_option "--JsonRpc.MaxLogsPerResponse" "$NETHERMIND_JSONRPC_MAX_LOGS_PER_RESPONSE"
append_option "--JsonRpc.MaxRequestBodySize" "$NETHERMIND_JSONRPC_MAX_REQUEST_BODY_SIZE"
append_option "--JsonRpc.MaxSimulateBlocksCap" "$NETHERMIND_JSONRPC_MAX_SIMULATE_BLOCKS_CAP"
append_option "--JsonRpc.MethodsLoggingFiltering" "$NETHERMIND_JSONRPC_METHODS_LOGGING_FILTERING"
append_option "--JsonRpc.Port" "$NETHERMIND_JSONRPC_PORT"
append_option "--JsonRpc.ReportIntervalSeconds" "$NETHERMIND_JSONRPC_REPORT_INTERVAL_SECONDS"
append_option "--JsonRpc.RequestQueueLimit" "$NETHERMIND_JSONRPC_REQUEST_QUEUE_LIMIT"
append_option "--JsonRpc.RpcRecorderBaseFilePath" "$NETHERMIND_JSONRPC_RPC_RECORDER_BASE_FILE_PATH"
append_option "--JsonRpc.RpcRecorderState" "$NETHERMIND_JSONRPC_RPC_RECORDER_STATE"
append_option "--JsonRpc.Timeout" "$NETHERMIND_JSONRPC_TIMEOUT"
append_option "--JsonRpc.UnsecureDevNoRpcAuthentication" "$NETHERMIND_JSONRPC_UNSECURE_DEV_NO_RPC_AUTHENTICATION"
append_option "--JsonRpc.WebSocketsPort" "$NETHERMIND_JSONRPC_WEBSOCKETS_PORT"
append_option "--KeyStore.BlockAuthorAccount" "$NETHERMIND_KEYSTORE_BLOCK_AUTHOR_ACCOUNT"
append_option "--KeyStore.Cipher" "$NETHERMIND_KEYSTORE_CIPHER"
append_option "--KeyStore.EnodeAccount" "$NETHERMIND_KEYSTORE_ENODE_ACCOUNT"
append_option "--KeyStore.EnodeKeyFile" "$NETHERMIND_KEYSTORE_ENODE_KEY_FILE"
append_option "--KeyStore.IVSize" "$NETHERMIND_KEYSTORE_IV_SIZE"
append_option "--KeyStore.Kdf" "$NETHERMIND_KEYSTORE_KDF"
append_option "--KeyStore.KdfparamsDklen" "$NETHERMIND_KEYSTORE_KDFPARAMS_DKLEN"
append_option "--KeyStore.KdfparamsN" "$NETHERMIND_KEYSTORE_KDFPARAMS_N"
append_option "--KeyStore.KdfparamsP" "$NETHERMIND_KEYSTORE_KDFPARAMS_P"
append_option "--KeyStore.KdfparamsR" "$NETHERMIND_KEYSTORE_KDFPARAMS_R"
append_option "--KeyStore.KdfparamsSaltLen" "$NETHERMIND_KEYSTORE_KDFPARAMS_SALT_LEN"
append_option "--KeyStore.KeyStoreDirectory" "$NETHERMIND_KEYSTORE_KEYSTORE_DIRECTORY"
append_option "--KeyStore.KeyStoreEncoding" "$NETHERMIND_KEYSTORE_KEYSTORE_ENCODING"
append_option "--KeyStore.PasswordFiles" "$NETHERMIND_KEYSTORE_PASSWORD_FILES"
append_option "--KeyStore.Passwords" "$NETHERMIND_KEYSTORE_PASSWORDS"
append_option "--KeyStore.SymmetricEncrypterBlockSize" "$NETHERMIND_KEYSTORE_SYMMETRIC_ENCRYPTER_BLOCK_SIZE"
append_option "--KeyStore.SymmetricEncrypterKeySize" "$NETHERMIND_KEYSTORE_SYMMETRIC_ENCRYPTER_KEY_SIZE"
append_option "--KeyStore.TestNodeKey" "$NETHERMIND_KEYSTORE_TEST_NODE_KEY"
append_option "--KeyStore.UnlockAccounts" "$NETHERMIND_KEYSTORE_UNLOCK_ACCOUNTS"
append_option "--Merge.BuilderRelayUrl" "$NETHERMIND_MERGE_BUILDER_RELAY_URL"
append_option "--Merge.CollectionsPerDecommit" "$NETHERMIND_MERGE_COLLECTIONS_PER_DECOMMIT"
append_option "--Merge.CompactMemory" "$NETHERMIND_MERGE_COMPACT_MEMORY"
append_option "--Merge.Enabled" "$NETHERMIND_MERGE_ENABLED"
append_option "--Merge.FinalTotalDifficulty" "$NETHERMIND_MERGE_FINAL_TOTAL_DIFFICULTY"
append_option "--Merge.NewPayloadTimeout" "$NETHERMIND_MERGE_NEW_PAYLOAD_TIMEOUT"
append_option "--Merge.PrioritizeBlockLatency" "$NETHERMIND_MERGE_PRIORITIZE_BLOCK_LATENCY"
append_option "--Merge.SecondsPerSlot" "$NETHERMIND_MERGE_SECONDS_PER_SLOT"
append_option "--Merge.SimulateBlockProduction" "$NETHERMIND_MERGE_SIMULATE_BLOCK_PRODUCTION"
append_option "--Merge.SweepMemory" "$NETHERMIND_MERGE_SWEEP_MEMORY"
append_option "--Merge.TerminalBlockHash" "$NETHERMIND_MERGE_TERMINAL_BLOCK_HASH"
append_option "--Merge.TerminalBlockNumber" "$NETHERMIND_MERGE_TERMINAL_BLOCK_NUMBER"
append_option "--Merge.TerminalTotalDifficulty" "$NETHERMIND_MERGE_TERMINAL_TOTAL_DIFFICULTY"
append_option "--Metrics.CountersEnabled" "$NETHERMIND_METRICS_COUNTERS_ENABLED"
append_option "--Metrics.EnableDbSizeMetrics" "$NETHERMIND_METRICS_ENABLE_DB_SIZE_METRICS"
append_option "--Metrics.Enabled" "$NETHERMIND_METRICS_ENABLED"
append_option "--Metrics.ExposeHost" "$NETHERMIND_METRICS_EXPOSE_HOST"
append_option "--Metrics.ExposePort" "$NETHERMIND_METRICS_EXPOSE_PORT"
append_option "--Metrics.IntervalSeconds" "$NETHERMIND_METRICS_INTERVAL_SECONDS"
append_option "--Metrics.NodeName" "$NETHERMIND_METRICS_NODE_NAME"
append_option "--Metrics.PushGatewayUrl" "$NETHERMIND_METRICS_PUSH_GATEWAY_URL"
append_option "--Mining.Enabled" "$NETHERMIND_MINING_ENABLED"
append_option "--Mining.ExtraData" "$NETHERMIND_MINING_EXTRA_DATA"
append_option "--Mining.MinGasPrice" "$NETHERMIND_MINING_MIN_GAS_PRICE"
append_option "--Mining.RandomizedBlocks" "$NETHERMIND_MINING_RANDOMIZED_BLOCKS"
append_option "--Mining.Signer" "$NETHERMIND_MINING_SIGNER"
append_option "--Mining.TargetBlockGasLimit" "$NETHERMIND_MINING_TARGET_BLOCK_GAS_LIMIT"
append_option "--Network.ActivePeersMaxCount" "$NETHERMIND_NETWORK_ACTIVE_PEERS_MAX_COUNT"
append_option "--Network.Bootnodes" "$NETHERMIND_NETWORK_BOOTNODES"
append_option "--Network.ClientIdMatcher" "$NETHERMIND_NETWORK_CLIENT_ID_MATCHER"
append_option "--Network.ConnectTimeoutMs" "$NETHERMIND_NETWORK_CONNECT_TIMEOUT_MS"
append_option "--Network.DiagTracerEnabled" "$NETHERMIND_NETWORK_DIAG_TRACER_ENABLED"
append_option "--Network.DisableDiscV4DnsFeeder" "$NETHERMIND_NETWORK_DISABLE_DISCV4_DNS_FEEDER"
append_option "--Network.DiscoveryDns" "$NETHERMIND_NETWORK_DISCOVERY_DNS"
append_option "--Network.DiscoveryPort" "$NETHERMIND_NETWORK_DISCOVERY_PORT"
append_option "--Network.EnableUPnP" "$NETHERMIND_NETWORK_ENABLE_UPNP"
append_option "--Network.ExternalIp" "$NETHERMIND_NETWORK_EXTERNAL_IP"
append_option "--Network.LocalIp" "$NETHERMIND_NETWORK_LOCAL_IP"
append_option "--Network.MaxActivePeers" "$NETHERMIND_NETWORK_MAX_ACTIVE_PEERS"
append_option "--Network.MaxNettyArenaCount" "$NETHERMIND_NETWORK_MAX_NETTY_ARENA_COUNT"
append_option "--Network.MaxOutgoingConnectPerSec" "$NETHERMIND_NETWORK_MAX_OUTGOING_CONNECT_PER_SEC"
append_option "--Network.NettyArenaOrder" "$NETHERMIND_NETWORK_NETTY_ARENA_ORDER"
append_option "--Network.NumConcurrentOutgoingConnects" "$NETHERMIND_NETWORK_NUM_CONCURRENT_OUTGOING_CONNECTS"
append_option "--Network.OnlyStaticPeers" "$NETHERMIND_NETWORK_ONLY_STATIC_PEERS"
append_option "--Network.P2PPort" "$NETHERMIND_NETWORK_P2P_PORT"
append_option "--Network.PriorityPeersMaxCount" "$NETHERMIND_NETWORK_PRIORITY_PEERS_MAX_COUNT"
append_option "--Network.ProcessingThreadCount" "$NETHERMIND_NETWORK_PROCESSING_THREAD_COUNT"
append_option "--Network.SimulateSendLatencyMs" "$NETHERMIND_NETWORK_SIMULATE_SEND_LATENCY_MS"
append_option "--Network.StaticPeers" "$NETHERMIND_NETWORK_STATIC_PEERS"
append_option "--Optimism.SequencerUrl" "$NETHERMIND_OPTIMISM_SEQUENCER_URL"
append_option "--Plugin.PluginOrder" "$NETHERMIND_PLUGIN_PLUGIN_ORDER"
append_option "--Pruning.AvailableSpaceCheckEnabled" "$NETHERMIND_PRUNING_AVAILABLE_SPACE_CHECK_ENABLED"
append_option "--Pruning.CacheMb" "$NETHERMIND_PRUNING_CACHE_MB"
append_option "--Pruning.Enabled" "$NETHERMIND_PRUNING_ENABLED"
append_option "--Pruning.FullPruningCompletionBehavior" "$NETHERMIND_PRUNING_FULL_PRUNING_COMPLETION_BEHAVIOR"
append_option "--Pruning.FullPruningDisableLowPriorityWrites" "$NETHERMIND_PRUNING_FULL_PRUNING_DISABLE_LOW_PRIORITY_WRITES"
append_option "--Pruning.FullPruningMaxDegreeOfParallelism" "$NETHERMIND_PRUNING_FULL_PRUNING_MAX_DEGREE_OF_PARALLELISM"
append_option "--Pruning.FullPruningMemoryBudgetMb" "$NETHERMIND_PRUNING_FULL_PRUNING_MEMORY_BUDGET_MB"
append_option "--Pruning.FullPruningMinimumDelayHours" "$NETHERMIND_PRUNING_FULL_PRUNING_MINIMUM_DELAY_HOURS"
append_option "--Pruning.FullPruningThresholdMb" "$NETHERMIND_PRUNING_FULL_PRUNING_THRESHOLD_MB"
append_option "--Pruning.FullPruningTrigger" "$NETHERMIND_PRUNING_FULL_PRUNING_TRIGGER"
append_option "--Pruning.Mode" "$NETHERMIND_PRUNING_MODE"
append_option "--Pruning.PersistenceInterval" "$NETHERMIND_PRUNING_PERSISTENCE_INTERVAL"
append_option "--Pruning.PruningBoundary" "$NETHERMIND_PRUNING_PRUNING_BOUNDARY"
append_option "--Pruning.TrackedPastKeyCountMemoryRatio" "$NETHERMIND_PRUNING_TRACKED_PAST_KEY_COUNT_MEMORY_RATIO"
append_option "--Receipt.CompactReceiptStore" "$NETHERMIND_RECEIPT_COMPACT_RECEIPT_STORE"
append_option "--Receipt.CompactTxIndex" "$NETHERMIND_RECEIPT_COMPACT_TX_INDEX"
append_option "--Receipt.ForceReceiptsMigration" "$NETHERMIND_RECEIPT_FORCE_RECEIPTS_MIGRATION"
append_option "--Receipt.MaxBlockDepth" "$NETHERMIND_RECEIPT_MAX_BLOCK_DEPTH"
append_option "--Receipt.ReceiptsMigration" "$NETHERMIND_RECEIPT_RECEIPTS_MIGRATION"
append_option "--Receipt.ReceiptsMigrationDegreeOfParallelism" "$NETHERMIND_RECEIPT_RECEIPTS_MIGRATION_DEGREE_OF_PARALLELISM"
append_option "--Receipt.StoreReceipts" "$NETHERMIND_RECEIPT_STORE_RECEIPTS"
append_option "--Receipt.TxLookupLimit" "$NETHERMIND_RECEIPT_TX_LOOKUP_LIMIT"
append_option "--Seq.ApiKey" "$NETHERMIND_SEQ_API_KEY"
append_option "--Seq.MinLevel" "$NETHERMIND_SEQ_MIN_LEVEL"
append_option "--Seq.ServerUrl" "$NETHERMIND_SEQ_SERVER_URL"
append_option "--Snapshot.Checksum" "$NETHERMIND_SNAPSHOT_CHECKSUM"
append_option "--Snapshot.DownloadUrl" "$NETHERMIND_SNAPSHOT_DOWNLOAD_URL"
append_option "--Snapshot.Enabled" "$NETHERMIND_SNAPSHOT_ENABLED"
append_option "--Snapshot.SnapshotDirectory" "$NETHERMIND_SNAPSHOT_SNAPSHOT_DIRECTORY"
append_option "--Snapshot.SnapshotFileName" "$NETHERMIND_SNAPSHOT_SNAPSHOT_FILE_NAME"
append_option "--Sync.AncientBodiesBarrier" "$NETHERMIND_SYNC_ANCIENT_BODIES_BARRIER"
append_option "--Sync.AncientReceiptsBarrier" "$NETHERMIND_SYNC_ANCIENT_RECEIPTS_BARRIER"
append_option "--Sync.BlocksDbTuneDbMode" "$NETHERMIND_SYNC_BLOCKS_DB_TUNE_DB_MODE"
append_option "--Sync.DownloadBodiesInFastSync" "$NETHERMIND_SYNC_DOWNLOAD_BODIES_IN_FAST_SYNC"
append_option "--Sync.DownloadHeadersInFastSync" "$NETHERMIND_SYNC_DOWNLOAD_HEADERS_IN_FAST_SYNC"
append_option "--Sync.DownloadReceiptsInFastSync" "$NETHERMIND_SYNC_DOWNLOAD_RECEIPTS_IN_FAST_SYNC"
append_option "--Sync.ExitOnSynced" "$NETHERMIND_SYNC_EXIT_ON_SYNCED"
append_option "--Sync.ExitOnSyncedWaitTimeSec" "$NETHERMIND_SYNC_EXIT_ON_SYNCED_WAIT_TIME_SEC"
append_option "--Sync.FastBlocks" "$NETHERMIND_SYNC_FAST_BLOCKS"
append_option "--Sync.FastSync" "$NETHERMIND_SYNC_FAST_SYNC"
append_option "--Sync.FastSyncCatchUpHeightDelta" "$NETHERMIND_SYNC_FAST_SYNC_CATCH_UP_HEIGHT_DELTA"
append_option "--Sync.FixReceipts" "$NETHERMIND_SYNC_FIX_RECEIPTS"
append_option "--Sync.FixTotalDifficulty" "$NETHERMIND_SYNC_FIX_TOTAL_DIFFICULTY"
append_option "--Sync.FixTotalDifficultyLastBlock" "$NETHERMIND_SYNC_FIX_TOTAL_DIFFICULTY_LAST_BLOCK"
append_option "--Sync.FixTotalDifficultyStartingBlock" "$NETHERMIND_SYNC_FIX_TOTAL_DIFFICULTY_STARTING_BLOCK"
append_option "--Sync.MallocTrimIntervalSec" "$NETHERMIND_SYNC_MALLOC_TRIM_INTERVAL_SEC"
append_option "--Sync.MaxAttemptsToUpdatePivot" "$NETHERMIND_SYNC_MAX_ATTEMPTS_TO_UPDATE_PIVOT"
append_option "--Sync.MaxProcessingThreads" "$NETHERMIND_SYNC_MAX_PROCESSING_THREADS"
append_option "--Sync.MultiSyncModeSelectorLoopTimerMs" "$NETHERMIND_SYNC_MULTI_SYNC_MODE_SELECTOR_LOOP_TIMER_MS"
append_option "--Sync.NetworkingEnabled" "$NETHERMIND_SYNC_NETWORKING_ENABLED"
append_option "--Sync.NonValidatorNode" "$NETHERMIND_SYNC_NON_VALIDATOR_NODE"
append_option "--Sync.PivotHash" "$NETHERMIND_SYNC_PIVOT_HASH"
append_option "--Sync.PivotNumber" "$NETHERMIND_SYNC_PIVOT_NUMBER"
append_option "--Sync.PivotTotalDifficulty" "$NETHERMIND_SYNC_PIVOT_TOTAL_DIFFICULTY"
append_option "--Sync.SnapServingEnabled" "$NETHERMIND_SYNC_SNAP_SERVING_ENABLED"
append_option "--Sync.SnapSync" "$NETHERMIND_SYNC_SNAP_SYNC"
append_option "--Sync.SnapSyncAccountRangePartitionCount" "$NETHERMIND_SYNC_SNAP_SYNC_ACCOUNT_RANGE_PARTITION_COUNT"
append_option "--Sync.StrictMode" "$NETHERMIND_SYNC_STRICT_MODE"
append_option "--Sync.SynchronizationEnabled" "$NETHERMIND_SYNC_SYNCHRONIZATION_ENABLED"
append_option "--Sync.TrieHealing" "$NETHERMIND_SYNC_TRIE_HEALING"
append_option "--Sync.TuneDbMode" "$NETHERMIND_SYNC_TUNE_DB_MODE"
append_option "--Sync.UseGethLimitsInFastBlocks" "$NETHERMIND_SYNC_USE_GETH_LIMITS_IN_FAST_BLOCKS"
append_option "--TraceStore.BlocksToKeep" "$NETHERMIND_TRACE_STORE_BLOCKS_TO_KEEP"
append_option "--TraceStore.DeserializationParallelization" "$NETHERMIND_TRACE_STORE_DESERIALIZATION_PARALLELIZATION"
append_option "--TraceStore.Enabled" "$NETHERMIND_TRACE_STORE_ENABLED"
append_option "--TraceStore.MaxDepth" "$NETHERMIND_TRACE_STORE_MAX_DEPTH"
append_option "--TraceStore.TraceTypes" "$NETHERMIND_TRACE_STORE_TRACE_TYPES"
append_option "--TraceStore.VerifySerialized" "$NETHERMIND_TRACE_STORE_VERIFY_SERIALIZED"
append_option "--TxPool.BlobCacheSize" "$NETHERMIND_TX_POOL_BLOB_CACHE_SIZE"
append_option "--TxPool.BlobsSupport" "$NETHERMIND_TX_POOL_BLOBS_SUPPORT"
append_option "--TxPool.GasLimit" "$NETHERMIND_TX_POOL_GAS_LIMIT"
append_option "--TxPool.HashCacheSize" "$NETHERMIND_TX_POOL_HASH_CACHE_SIZE"
append_option "--TxPool.InMemoryBlobPoolSize" "$NETHERMIND_TX_POOL_IN_MEMORY_BLOB_POOL_SIZE"
append_option "--TxPool.MaxPendingBlobTxsPerSender" "$NETHERMIND_TX_POOL_MAX_PENDING_BLOB_TXS_PER_SENDER"
append_option "--TxPool.MaxPendingTxsPerSender" "$NETHERMIND_TX_POOL_MAX_PENDING_TXS_PER_SENDER"
append_option "--TxPool.MinBaseFeeThreshold" "$NETHERMIND_TX_POOL_MIN_BASE_FEE_THRESHOLD"
append_option "--TxPool.PeerNotificationThreshold" "$NETHERMIND_TX_POOL_PEER_NOTIFICATION_THRESHOLD"
append_option "--TxPool.PersistentBlobStorageSize" "$NETHERMIND_TX_POOL_PERSISTENT_BLOB_STORAGE_SIZE"
append_option "--TxPool.ReportMinutes" "$NETHERMIND_TX_POOL_REPORT_MINUTES"
append_option "--TxPool.Size" "$NETHERMIND_TX_POOL_SIZE"
append_option "--Wallet.DevAccounts" "$NETHERMIND_WALLET_DEV_ACCOUNTS"

echo "Using Options: nethermind $OPTIONS"

# CI problem again, with cache

exec nethermind $OPTIONS
