#!/usr/bin/env bash 

set -e 

display_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --conf-file FILE, -e FILE   Path to .conf formatted configuration file."   
    echo "  --help, -h                    Displays this help text and exits."
    echo "  --version, -v                 Displays the version and exits."
    exit 0
}

display_version() {
    local version=$(basename "$(dirname "$(realpath "$0")")")
    echo "$0 version $version"
    exit 0
}

CONFIG_FILES=()
HELP=false
VERSION=false

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --conf-file|-e)
            CONFIG_FILES+=("$2")
            shift 2
            ;;
        --help|-h)
            HELP=true
            shift
            ;;
        --version|-v)
            VERSION=true
            shift
            ;;  
        *)
            echo "Error: Unknown option $1"
            display_help
            ;;
    esac
done

if [ "$HELP" = true ]; then
    display_help
fi

if [ "$VERSION" = true ]; then
    display_version
fi

if [[ ${#CONFIG_FILES[@]} -eq 0 ]]; then
    echo "Error: At least one --conf-file option is required"
    display_help
fi

for CONFIG_FILE in "${CONFIG_FILES[@]}"; do
    if [[ -f "$CONFIG_FILE" ]]; then
        echo "Starting with configuration from $CONFIG_FILE"
        source "$CONFIG_FILE"
    else
        echo "Error: Configuration file $CONFIG_FILE not found."
        exit 1
    fi
done

OPTIONS=""

append_option() {
  local option=$1
  local value=$2
  if [ -n "$value" ]; then
    OPTIONS="$OPTIONS $option=$value"
  fi
}



append_option "--datadir" "$datadir"
append_option "--config" "$config"
append_option "--baseDbPath" "$base_db_path"
append_option "--log" "$log"
append_option "--configsDirectory" "$configs_directory"
append_option "--loggerConfigSource" "$logger_config_source"
append_option "--pluginsDirectory" "$plugins_directory"
append_option   "--Aura.AllowAuRaPrivateChains" "$aura_allow_aura_private_chains"
append_option   "--Aura.ForceSealing" "$aura_force_sealing"
append_option "--Aura.Minimum2MlnGasPerBlockWhenUsingBlockGasLimitContract" "$aura_minimum_2mln_gas_per_block_when_using_block_gas_limit_contract"
append_option "--Aura.TxPriorityConfigFilePath" "$aura_tx_priority_config_file_path"
append_option "--Aura.TxPriorityContractAddress" "$aura_tx_priority_contract_address"
append_option "--Blocks.BlockProductionTimeoutMs" "$blocks_block_production_timeout_ms"
append_option "--Blocks.ExtraData" "$blocks_extra_data"
append_option "--Blocks.GenesisTimeoutMs" "$blocks_genesis_timeout_ms"
append_option "--Blocks.MinGasPrice" "$blocks_min_gas_price"
append_option   "--Blocks.PreWarmStateOnBlockProcessing" "$blocks_pre_warm_state_on_block_processing"
append_option   "--Blocks.RandomizedBlocks" "$blocks_randomized_blocks"
append_option "--Blocks.SecondsPerSlot" "$blocks_seconds_per_slot"
append_option "--Blocks.TargetBlockGasLimit" "$blocks_target_block_gas_limit"
append_option   "--Bloom.Index" "$bloom_index"
append_option "--Bloom.IndexLevelBucketSizes" "$bloom_index_level_bucket_sizes"
append_option   "--Bloom.Migration" "$bloom_migration"
append_option   "--Bloom.MigrationStatistics" "$bloom_migration_statistics"
append_option "--CensorshipDetector.AddressesForCensorshipDetection" "$censorship_detector_addresses_for_censorship_detection"
append_option "--CensorshipDetector.BlockCensorshipThreshold" "$censorship_detector_block_censorship_threshold"
append_option   "--CensorshipDetector.Enabled" "$censorship_detector_enabled"
append_option "--Db.AdditionalRocksDbOptions" "$db_additional_rocks_db_options"
append_option "--Db.AdviseRandomOnOpen" "$db_advise_random_on_open"
append_option "--Db.AllowMmapReads" "$db_allow_mmap_reads"
append_option "--Db.BlobTransactionsDbBlockCacheSize" "$db_blob_transactions_db_block_cache_size"
append_option "--Db.BlockCacheSize" "$db_block_cache_size"
append_option "--Db.BlockInfosDbAdditionalRocksDbOptions" "$db_block_infos_db_additional_rocks_db_options"
append_option "--Db.BlockInfosDbBlockCacheSize" "$db_block_infos_db_block_cache_size"
append_option "--Db.BlockInfosDbBlockSize" "$db_block_infos_db_block_size"
append_option "--Db.BlockInfosDbCacheIndexAndFilterBlocks" "$db_block_infos_db_cache_index_and_filter_blocks"
append_option "--Db.BlockInfosDbCompactionReadAhead" "$db_block_infos_db_compaction_read_ahead"
append_option "--Db.BlockInfosDbMaxBytesPerSec" "$db_block_infos_db_max_bytes_per_sec"
append_option "--Db.BlockInfosDbMaxOpenFiles" "$db_block_infos_db_max_open_files"
append_option "--Db.BlockInfosDbUseDirectIoForFlushAndCompactions" "$db_block_infos_db_use_direct_io_for_flush_and_compactions"
append_option "--Db.BlockInfosDbUseDirectReads" "$db_block_infos_db_use_direct_reads"
append_option "--Db.BlockInfosDbWriteBufferNumber" "$db_block_infos_db_write_buffer_number"
append_option "--Db.BlockInfosDbWriteBufferSize" "$db_block_infos_db_write_buffer_size"
append_option "--Db.BlockNumbersDbAdditionalRocksDbOptions" "$db_block_numbers_db_additional_rocks_db_options"
append_option "--Db.BlockNumbersDbBlockCacheSize" "$db_block_numbers_db_block_cache_size"
append_option "--Db.BlockNumbersDbBlockSize" "$db_block_numbers_db_block_size"
append_option "--Db.BlockNumbersDbCacheIndexAndFilterBlocks" "$db_block_numbers_db_cache_index_and_filter_blocks"
append_option "--Db.BlockNumbersDbCompactionReadAhead" "$db_block_numbers_db_compaction_read_ahead"
append_option "--Db.BlockNumbersDbMaxBytesForLevelBase" "$db_block_numbers_db_max_bytes_for_level_base"
append_option "--Db.BlockNumbersDbMaxBytesPerSec" "$db_block_numbers_db_max_bytes_per_sec"
append_option "--Db.BlockNumbersDbMaxOpenFiles" "$db_block_numbers_db_max_open_files"
append_option "--Db.BlockNumbersDbRowCacheSize" "$db_block_numbers_db_row_cache_size"
append_option "--Db.BlockNumbersDbUseDirectIoForFlushAndCompactions" "$db_block_numbers_db_use_direct_io_for_flush_and_compactions"
append_option "--Db.BlockNumbersDbUseDirectReads" "$db_block_numbers_db_use_direct_reads"
append_option "--Db.BlockNumbersDbUseHashIndex" "$db_block_numbers_db_use_hash_index"
append_option "--Db.BlockNumbersDbUseHashSkipListMemtable" "$db_block_numbers_db_use_hash_skip_list_memtable"
append_option "--Db.BlockNumbersDbWriteBufferNumber" "$db_block_numbers_db_write_buffer_number"
append_option "--Db.BlockNumbersDbWriteBufferSize" "$db_block_numbers_db_write_buffer_size"
append_option "--Db.BlockRestartInterval" "$db_block_restart_interval"
append_option "--Db.BlockSize" "$db_block_size"
append_option "--Db.BlocksBlockSize" "$db_blocks_block_size"
append_option "--Db.BlocksDbAdditionalRocksDbOptions" "$db_blocks_db_additional_rocks_db_options"
append_option "--Db.BlocksDbBlockCacheSize" "$db_blocks_db_block_cache_size"
append_option "--Db.BlocksDbCacheIndexAndFilterBlocks" "$db_blocks_db_cache_index_and_filter_blocks"
append_option "--Db.BlocksDbCompactionReadAhead" "$db_blocks_db_compaction_read_ahead"
append_option "--Db.BlocksDbMaxBytesPerSec" "$db_blocks_db_max_bytes_per_sec"
append_option "--Db.BlocksDbMaxOpenFiles" "$db_blocks_db_max_open_files"
append_option "--Db.BlocksDbUseDirectIoForFlushAndCompactions" "$db_blocks_db_use_direct_io_for_flush_and_compactions"
append_option "--Db.BlocksDbUseDirectReads" "$db_blocks_db_use_direct_reads"
append_option "--Db.BlocksDbWriteBufferNumber" "$db_blocks_db_write_buffer_number"
append_option "--Db.BlocksDbWriteBufferSize" "$db_blocks_db_write_buffer_size"
append_option "--Db.BloomDbAdditionalRocksDbOptions" "$db_bloom_db_additional_rocks_db_options"
append_option "--Db.BloomDbBlockCacheSize" "$db_bloom_db_block_cache_size"
append_option "--Db.BloomDbCacheIndexAndFilterBlocks" "$db_bloom_db_cache_index_and_filter_blocks"
append_option "--Db.BloomDbMaxBytesPerSec" "$db_bloom_db_max_bytes_per_sec"
append_option "--Db.BloomDbMaxOpenFiles" "$db_bloom_db_max_open_files"
append_option "--Db.BloomDbWriteBufferNumber" "$db_bloom_db_write_buffer_number"
append_option "--Db.BloomDbWriteBufferSize" "$db_bloom_db_write_buffer_size"
append_option "--Db.BloomFilterBitsPerKey" "$db_bloom_filter_bits_per_key"
append_option "--Db.BytesPerSync" "$db_bytes_per_sync"
append_option "--Db.CacheIndexAndFilterBlocks" "$db_cache_index_and_filter_blocks"
append_option "--Db.CodeCompactionReadAhead" "$db_code_compaction_read_ahead"
append_option "--Db.CodeDbAdditionalRocksDbOptions" "$db_code_db_additional_rocks_db_options"
append_option "--Db.CodeDbBlockCacheSize" "$db_code_db_block_cache_size"
append_option "--Db.CodeDbBlockSize" "$db_code_db_block_size"
append_option "--Db.CodeDbCacheIndexAndFilterBlocks" "$db_code_db_cache_index_and_filter_blocks"
append_option "--Db.CodeDbMaxBytesPerSec" "$db_code_db_max_bytes_per_sec"
append_option "--Db.CodeDbMaxOpenFiles" "$db_code_db_max_open_files"
append_option "--Db.CodeDbRowCacheSize" "$db_code_db_row_cache_size"
append_option "--Db.CodeDbUseHashIndex" "$db_code_db_use_hash_index"
append_option "--Db.CodeDbUseHashSkipListMemtable" "$db_code_db_use_hash_skip_list_memtable"
append_option "--Db.CodeDbWriteBufferNumber" "$db_code_db_write_buffer_number"
append_option "--Db.CodeDbWriteBufferSize" "$db_code_db_write_buffer_size"
append_option "--Db.CodeUseDirectIoForFlushAndCompactions" "$db_code_use_direct_io_for_flush_and_compactions"
append_option "--Db.CodeUseDirectReads" "$db_code_use_direct_reads"
append_option "--Db.CompactionReadAhead" "$db_compaction_read_ahead"
append_option "--Db.CompressibilityHint" "$db_compressibility_hint"
append_option "--Db.DataBlockIndexUtilRatio" "$db_data_block_index_util_ratio"
append_option "--Db.DisableCompression" "$db_disable_compression"
append_option "--Db.EnableDbStatistics" "$db_enable_db_statistics"
append_option "--Db.EnableFileWarmer" "$db_enable_file_warmer"
append_option "--Db.EnableMetricsUpdater" "$db_enable_metrics_updater"
append_option "--Db.HeadersDbAdditionalRocksDbOptions" "$db_headers_db_additional_rocks_db_options"
append_option "--Db.HeadersDbBlockCacheSize" "$db_headers_db_block_cache_size"
append_option "--Db.HeadersDbBlockSize" "$db_headers_db_block_size"
append_option "--Db.HeadersDbCacheIndexAndFilterBlocks" "$db_headers_db_cache_index_and_filter_blocks"
append_option "--Db.HeadersDbCompactionReadAhead" "$db_headers_db_compaction_read_ahead"
append_option "--Db.HeadersDbMaxBytesForLevelBase" "$db_headers_db_max_bytes_for_level_base"
append_option "--Db.HeadersDbMaxBytesPerSec" "$db_headers_db_max_bytes_per_sec"
append_option "--Db.HeadersDbMaxOpenFiles" "$db_headers_db_max_open_files"
append_option "--Db.HeadersDbUseDirectIoForFlushAndCompactions" "$db_headers_db_use_direct_io_for_flush_and_compactions"
append_option "--Db.HeadersDbUseDirectReads" "$db_headers_db_use_direct_reads"
append_option "--Db.HeadersDbWriteBufferNumber" "$db_headers_db_write_buffer_number"
append_option "--Db.HeadersDbWriteBufferSize" "$db_headers_db_write_buffer_size"
append_option "--Db.LevelCompactionDynamicLevelBytes" "$db_level_compaction_dynamic_level_bytes"
append_option "--Db.MaxBytesForLevelBase" "$db_max_bytes_for_level_base"
append_option "--Db.MaxBytesForLevelMultiplier" "$db_max_bytes_for_level_multiplier"
append_option "--Db.MaxBytesPerSec" "$db_max_bytes_per_sec"
append_option "--Db.MaxCompactionBytes" "$db_max_compaction_bytes"
append_option "--Db.MaxOpenFiles" "$db_max_open_files"
append_option "--Db.MaxWriteBufferSizeToMaintain" "$db_max_write_buffer_size_to_maintain"
append_option "--Db.MemtablePrefixBloomSizeRatio" "$db_memtable_prefix_bloom_size_ratio"
append_option "--Db.MetadataCompactionReadAhead" "$db_metadata_compaction_read_ahead"
append_option "--Db.MetadataDbAdditionalRocksDbOptions" "$db_metadata_db_additional_rocks_db_options"
append_option "--Db.MetadataDbBlockCacheSize" "$db_metadata_db_block_cache_size"
append_option "--Db.MetadataDbBlockSize" "$db_metadata_db_block_size"
append_option "--Db.MetadataDbCacheIndexAndFilterBlocks" "$db_metadata_db_cache_index_and_filter_blocks"
append_option "--Db.MetadataDbMaxBytesPerSec" "$db_metadata_db_max_bytes_per_sec"
append_option "--Db.MetadataDbMaxOpenFiles" "$db_metadata_db_max_open_files"
append_option "--Db.MetadataDbWriteBufferNumber" "$db_metadata_db_write_buffer_number"
append_option "--Db.MetadataDbWriteBufferSize" "$db_metadata_db_write_buffer_size"
append_option "--Db.MetadataUseDirectIoForFlushAndCompactions" "$db_metadata_use_direct_io_for_flush_and_compactions"
append_option "--Db.MetadataUseDirectReads" "$db_metadata_use_direct_reads"
append_option "--Db.MinWriteBufferNumberToMerge" "$db_min_write_buffer_number_to_merge"
append_option "--Db.OnlyCompressLastLevel" "$db_only_compress_last_level"
append_option "--Db.OptimizeFiltersForHits" "$db_optimize_filters_for_hits"
append_option "--Db.PendingTxsDbAdditionalRocksDbOptions" "$db_pending_txs_db_additional_rocks_db_options"
append_option "--Db.PendingTxsDbBlockCacheSize" "$db_pending_txs_db_block_cache_size"
append_option "--Db.PendingTxsDbBlockSize" "$db_pending_txs_db_block_size"
append_option "--Db.PendingTxsDbCacheIndexAndFilterBlocks" "$db_pending_txs_db_cache_index_and_filter_blocks"
append_option "--Db.PendingTxsDbCompactionReadAhead" "$db_pending_txs_db_compaction_read_ahead"
append_option "--Db.PendingTxsDbMaxBytesPerSec" "$db_pending_txs_db_max_bytes_per_sec"
append_option "--Db.PendingTxsDbMaxOpenFiles" "$db_pending_txs_db_max_open_files"
append_option "--Db.PendingTxsDbUseDirectIoForFlushAndCompactions" "$db_pending_txs_db_use_direct_io_for_flush_and_compactions"
append_option "--Db.PendingTxsDbUseDirectReads" "$db_pending_txs_db_use_direct_reads"
append_option "--Db.PendingTxsDbWriteBufferNumber" "$db_pending_txs_db_write_buffer_number"
append_option "--Db.PendingTxsDbWriteBufferSize" "$db_pending_txs_db_write_buffer_size"
append_option "--Db.PrefixExtractorLength" "$db_prefix_extractor_length"
append_option "--Db.ReadAheadSize" "$db_read_ahead_size"
append_option "--Db.ReceiptsDbAdditionalRocksDbOptions" "$db_receipts_db_additional_rocks_db_options"
append_option "--Db.ReceiptsDbBlockCacheSize" "$db_receipts_db_block_cache_size"
append_option "--Db.ReceiptsDbBlockSize" "$db_receipts_db_block_size"
append_option "--Db.ReceiptsDbCacheIndexAndFilterBlocks" "$db_receipts_db_cache_index_and_filter_blocks"
append_option "--Db.ReceiptsDbCompactionReadAhead" "$db_receipts_db_compaction_read_ahead"
append_option "--Db.ReceiptsDbCompressibilityHint" "$db_receipts_db_compressibility_hint"
append_option "--Db.ReceiptsDbMaxBytesPerSec" "$db_receipts_db_max_bytes_per_sec"
append_option "--Db.ReceiptsDbMaxOpenFiles" "$db_receipts_db_max_open_files"
append_option "--Db.ReceiptsDbTargetFileSizeBase" "$db_receipts_db_target_file_size_base"
append_option "--Db.ReceiptsDbUseDirectIoForFlushAndCompactions" "$db_receipts_db_use_direct_io_for_flush_and_compactions"
append_option "--Db.ReceiptsDbUseDirectReads" "$db_receipts_db_use_direct_reads"
append_option "--Db.ReceiptsDbWriteBufferNumber" "$db_receipts_db_write_buffer_number"
append_option "--Db.ReceiptsDbWriteBufferSize" "$db_receipts_db_write_buffer_size"
append_option "--Db.RecycleLogFileNum" "$db_recycle_log_file_num"
append_option "--Db.RowCacheSize" "$db_row_cache_size"
append_option "--Db.SharedBlockCacheSize" "$db_shared_block_cache_size"
append_option "--Db.SkipMemoryHintSetting" "$db_skip_memory_hint_setting"
append_option "--Db.StateDbAdditionalRocksDbOptions" "$db_state_db_additional_rocks_db_options"
append_option "--Db.StateDbAdviseRandomOnOpen" "$db_state_db_advise_random_on_open"
append_option "--Db.StateDbAllowMmapReads" "$db_state_db_allow_mmap_reads"
append_option "--Db.StateDbBlockCacheSize" "$db_state_db_block_cache_size"
append_option "--Db.StateDbBlockRestartInterval" "$db_state_db_block_restart_interval"
append_option "--Db.StateDbBlockSize" "$db_state_db_block_size"
append_option "--Db.StateDbBloomFilterBitsPerKey" "$db_state_db_bloom_filter_bits_per_key"
append_option "--Db.StateDbCacheIndexAndFilterBlocks" "$db_state_db_cache_index_and_filter_blocks"
append_option "--Db.StateDbCompactionReadAhead" "$db_state_db_compaction_read_ahead"
append_option "--Db.StateDbCompressibilityHint" "$db_state_db_compressibility_hint"
append_option "--Db.StateDbDataBlockIndexUtilRatio" "$db_state_db_data_block_index_util_ratio"
append_option "--Db.StateDbDisableCompression" "$db_state_db_disable_compression"
append_option "--Db.StateDbEnableFileWarmer" "$db_state_db_enable_file_warmer"
append_option "--Db.StateDbMaxBytesForLevelBase" "$db_state_db_max_bytes_for_level_base"
append_option "--Db.StateDbMaxBytesForLevelMultiplier" "$db_state_db_max_bytes_for_level_multiplier"
append_option "--Db.StateDbMaxBytesPerSec" "$db_state_db_max_bytes_per_sec"
append_option "--Db.StateDbMaxCompactionBytes" "$db_state_db_max_compaction_bytes"
append_option "--Db.StateDbMaxOpenFiles" "$db_state_db_max_open_files"
append_option "--Db.StateDbMaxWriteBufferSizeToMaintain" "$db_state_db_max_write_buffer_size_to_maintain"
append_option "--Db.StateDbMemtablePrefixBloomSizeRatio" "$db_state_db_memtable_prefix_bloom_size_ratio"
append_option "--Db.StateDbMinWriteBufferNumberToMerge" "$db_state_db_min_write_buffer_number_to_merge"
append_option "--Db.StateDbOnlyCompressLastLevel" "$db_state_db_only_compress_last_level"
append_option "--Db.StateDbOptimizeFiltersForHits" "$db_state_db_optimize_filters_for_hits"
append_option "--Db.StateDbPrefixExtractorLength" "$db_state_db_prefix_extractor_length"
append_option "--Db.StateDbRowCacheSize" "$db_state_db_row_cache_size"
append_option "--Db.StateDbTargetFileSizeMultiplier" "$db_state_db_target_file_size_multiplier"
append_option "--Db.StateDbUseDirectIoForFlushAndCompactions" "$db_state_db_use_direct_io_for_flush_and_compactions"
append_option "--Db.StateDbUseDirectReads" "$db_state_db_use_direct_reads"
append_option "--Db.StateDbUseHashIndex" "$db_state_db_use_hash_index"
append_option "--Db.StateDbUseHashSkipListMemtable" "$db_state_db_use_hash_skip_list_memtable"
append_option "--Db.StateDbUseLz4" "$db_state_db_use_lz4"
append_option "--Db.StateDbUseRibbonFilterStartingFromLevel" "$db_state_db_use_ribbon_filter_starting_from_level"
append_option "--Db.StateDbUseTwoLevelIndex" "$db_state_db_use_two_level_index"
append_option "--Db.StateDbVerifyChecksum" "$db_state_db_verify_checksum"
append_option "--Db.StateDbWriteBufferNumber" "$db_state_db_write_buffer_number"
append_option "--Db.StateDbWriteBufferSize" "$db_state_db_write_buffer_size"
append_option "--Db.StatsDumpPeriodSec" "$db_stats_dump_period_sec"
append_option "--Db.TargetFileSizeBase" "$db_target_file_size_base"
append_option "--Db.TargetFileSizeMultiplier" "$db_target_file_size_multiplier"
append_option "--Db.UseDirectIoForFlushAndCompactions" "$db_use_direct_io_for_flush_and_compactions"
append_option "--Db.UseDirectReads" "$db_use_direct_reads"
append_option "--Db.UseHashIndex" "$db_use_hash_index"
append_option "--Db.UseHashSkipListMemtable" "$db_use_hash_skip_list_memtable"
append_option "--Db.UseLz4" "$db_use_lz4"
append_option "--Db.UseRibbonFilterStartingFromLevel" "$db_use_ribbon_filter_starting_from_level"
append_option "--Db.UseTwoLevelIndex" "$db_use_two_level_index"
append_option "--Db.VerifyChecksum" "$db_verify_checksum"
append_option "--Db.WriteAheadLogSync" "$db_write_ahead_log_sync"
append_option "--Db.WriteBufferNumber" "$db_write_buffer_number"
append_option "--Db.WriteBufferSize" "$db_write_buffer_size"
append_option "--Discovery.BootnodePongTimeout" "$discovery_bootnode_pong_timeout"
append_option "--Discovery.Bootnodes" "$discovery_bootnodes"
append_option "--Discovery.BucketSize" "$discovery_bucket_size"
append_option "--Discovery.Concurrency" "$discovery_concurrency"
append_option "--Discovery.DiscoveryInterval" "$discovery_discovery_interval"
append_option "--Discovery.DiscoveryNewCycleWaitTime" "$discovery_discovery_new_cycle_wait_time"
append_option "--Discovery.DiscoveryPersistenceInterval" "$discovery_discovery_persistence_interval"
append_option "--Discovery.DiscoveryVersion" "$discovery_discovery_version"
append_option "--Discovery.DropFullBucketNodeProbability" "$discovery_drop_full_bucket_node_probability"
append_option "--Discovery.EvictionCheckInterval" "$discovery_eviction_check_interval"
append_option "--Discovery.MaxDiscoveryRounds" "$discovery_max_discovery_rounds"
append_option "--Discovery.MaxNodeLifecycleManagersCount" "$discovery_max_node_lifecycle_managers_count"
append_option "--Discovery.MaxOutgoingMessagePerSecond" "$discovery_max_outgoing_message_per_second"
append_option "--Discovery.NodeLifecycleManagersCleanupCount" "$discovery_node_lifecycle_managers_cleanup_count"
append_option "--Discovery.PingRetryCount" "$discovery_ping_retry_count"
append_option "--Discovery.PongTimeout" "$discovery_pong_timeout"
append_option "--Discovery.SendNodeTimeout" "$discovery_send_node_timeout"
append_option "--Discovery.UdpChannelCloseTimeout" "$discovery_udp_channel_close_timeout"
append_option "--EthStats.Contact" "$ethstats_contact"
append_option   "--EthStats.Enabled" "$ethstats_enabled"
append_option "--EthStats.Name" "$ethstats_name"
append_option "--EthStats.Secret" "$ethstats_secret"
append_option "--EthStats.SendInterval" "$ethstats_send_interval"
append_option "--EthStats.Server" "$ethstats_server"
append_option   "--HealthChecks.Enabled" "$healthchecks_enabled"
append_option "--HealthChecks.LowStorageCheckAwaitOnStartup" "$healthchecks_low_storage_check_await_on_startup"
append_option "--HealthChecks.LowStorageSpaceShutdownThreshold" "$healthchecks_low_storage_space_shutdown_threshold"
append_option "--HealthChecks.LowStorageSpaceWarningThreshold" "$healthchecks_low_storage_space_warning_threshold"
append_option "--HealthChecks.MaxIntervalClRequestTime" "$healthchecks_max_interval_cl_request_time"
append_option "--HealthChecks.MaxIntervalWithoutProcessedBlock" "$healthchecks_max_interval_without_processed_block"
append_option "--HealthChecks.MaxIntervalWithoutProducedBlock" "$healthchecks_max_interval_without_produced_block"
append_option "--HealthChecks.PollingInterval" "$healthchecks_polling_interval"
append_option "--HealthChecks.Slug" "$healthchecks_slug"
append_option   "--HealthChecks.UIEnabled" "$healthchecks_ui_enabled"
append_option   "--HealthChecks.WebhooksEnabled" "$healthchecks_webhooks_enabled"
append_option "--HealthChecks.WebhooksPayload" "$healthchecks_webhooks_payload"
append_option "--HealthChecks.WebhooksRestorePayload" "$healthchecks_webhooks_restore_payload"
append_option "--HealthChecks.WebhooksUri" "$healthchecks_webhooks_uri"
append_option "--Hive.BlocksDir" "$hive_blocks_dir"
append_option "--Hive.ChainFile" "$hive_chain_file"
append_option   "--Hive.Enabled" "$hive_enabled"
append_option "--Hive.GenesisFilePath" "$hive_genesis_file_path"
append_option "--Hive.KeysDir" "$hive_keys_dir"
append_option "--Init.AutoDump" "$init_auto_dump"
append_option "--Init.BackgroundTaskConcurrency" "$init_background_task_concurrency"
append_option "--Init.BadBlocksStored" "$init_bad_blocks_stored"
append_option "--Init.BaseDbPath" "$init_base_db_path"
append_option "--Init.ChainSpecPath" "$init_chain_spec_path"
append_option "--Init.DiagnosticMode" "$init_diagnostic_mode"
append_option   "--Init.DisableGcOnNewPayload" "$init_disable_gc_on_new_payload"
append_option   "--Init.DisableMallocOpts" "$init_disable_malloc_opts"
append_option   "--Init.DiscoveryEnabled" "$init_discovery_enabled"
append_option   "--Init.EnableUnsecuredDevWallet" "$init_enable_unsecured_dev_wallet"
append_option "--Init.ExitOnBlockNumber" "$init_exit_on_block_number"
append_option "--Init.GenesisHash" "$init_genesis_hash"
append_option "--Init.HiveChainSpecPath" "$init_hive_chain_spec_path"
append_option   "--Init.IsMining" "$init_is_mining"
append_option   "--Init.KeepDevWalletInMemory" "$init_keep_dev_wallet_in_memory"
append_option "--Init.KzgSetupPath" "$init_kzg_setup_path"
append_option "--Init.LogDirectory" "$init_log_directory"
append_option "--Init.LogFileName" "$init_log_file_name"
append_option "--Init.LogRules" "$init_log_rules"
append_option "--Init.MemoryHint" "$init_memory_hint"
append_option   "--Init.PeerManagerEnabled" "$init_peer_manager_enabled"
append_option   "--Init.ProcessingEnabled" "$init_processing_enabled"
append_option   "--Init.ReceiptsMigration" "$init_receipts_migration"
append_option "--Init.RpcDbUrl" "$init_rpc_db_url"
append_option "--Init.StateDbKeyScheme" "$init_state_db_key_scheme"
append_option "--Init.StaticNodesPath" "$init_static_nodes_path"
append_option   "--Init.StoreReceipts" "$init_store_receipts"
append_option   "--Init.WebSocketsEnabled" "$init_websockets_enabled"
append_option "--JsonRpc.AdditionalRpcUrls" "$jsonrpc_additional_rpc_urls"
append_option   "--JsonRpc.BufferResponses" "$jsonrpc_buffer_responses"
append_option "--JsonRpc.CallsFilterFilePath" "$jsonrpc_calls_filter_file_path"
append_option   "--JsonRpc.Enabled" "$jsonrpc_enabled"
append_option "--JsonRpc.EnabledModules" "$jsonrpc_enabled_modules"
append_option "--JsonRpc.EngineEnabledModules" "$jsonrpc_engine_enabled_modules"
append_option "--JsonRpc.EngineHost" "$jsonrpc_engine_host"
append_option "--JsonRpc.EnginePort" "$jsonrpc_engine_port"
append_option "--JsonRpc.EstimateErrorMargin" "$jsonrpc_estimate_error_margin"
append_option "--JsonRpc.EthModuleConcurrentInstances" "$jsonrpc_eth_module_concurrent_instances"
append_option "--JsonRpc.GasCap" "$jsonrpc_gas_cap"
append_option "--JsonRpc.Host" "$jsonrpc_host"
append_option "--JsonRpc.IpcUnixDomainSocketPath" "$jsonrpc_ipc_unix_domain_socket_path"
append_option "--JsonRpc.JwtSecretFile" "$jsonrpc_jwt_secret_file"
append_option "--JsonRpc.MaxBatchResponseBodySize" "$jsonrpc_max_batch_response_body_size"
append_option "--JsonRpc.MaxBatchSize" "$jsonrpc_max_batch_size"
append_option "--JsonRpc.MaxLoggedRequestParametersCharacters" "$jsonrpc_max_logged_request_parameters_characters"
append_option "--JsonRpc.MaxLogsPerResponse" "$jsonrpc_max_logs_per_response"
append_option "--JsonRpc.MaxRequestBodySize" "$jsonrpc_max_request_body_size"
append_option "--JsonRpc.MaxSimulateBlocksCap" "$jsonrpc_max_simulate_blocks_cap"
append_option "--JsonRpc.MethodsLoggingFiltering" "$jsonrpc_methods_logging_filtering"
append_option "--JsonRpc.Port" "$jsonrpc_port"
append_option "--JsonRpc.ReportIntervalSeconds" "$jsonrpc_report_interval_seconds"
append_option "--JsonRpc.RequestQueueLimit" "$jsonrpc_request_queue_limit"
append_option "--JsonRpc.RpcRecorderBaseFilePath" "$jsonrpc_rpc_recorder_base_file_path"
append_option "--JsonRpc.RpcRecorderState" "$jsonrpc_rpc_recorder_state"
append_option "--JsonRpc.Timeout" "$jsonrpc_timeout"
append_option   "--JsonRpc.UnsecureDevNoRpcAuthentication" "$jsonrpc_unsecure_dev_no_rpc_authentication"
append_option "--JsonRpc.WebSocketsPort" "$jsonrpc_websockets_port"
append_option "--KeyStore.BlockAuthorAccount" "$keystore_block_author_account"
append_option "--KeyStore.Cipher" "$keystore_cipher"
append_option "--KeyStore.EnodeAccount" "$keystore_enode_account"
append_option "--KeyStore.EnodeKeyFile" "$keystore_enode_key_file"
append_option "--KeyStore.IVSize" "$keystore_iv_size"
append_option "--KeyStore.Kdf" "$keystore_kdf"
append_option "--KeyStore.KdfparamsDklen" "$keystore_kdfparams_dklen"
append_option "--KeyStore.KdfparamsN" "$keystore_kdfparams_n"
append_option "--KeyStore.KdfparamsP" "$keystore_kdfparams_p"
append_option "--KeyStore.KdfparamsR" "$keystore_kdfparams_r"
append_option "--KeyStore.KdfparamsSaltLen" "$keystore_kdfparams_salt_len"
append_option "--KeyStore.KeyStoreDirectory" "$keystore_keystore_directory"
append_option "--KeyStore.KeyStoreEncoding" "$keystore_keystore_encoding"
append_option "--KeyStore.PasswordFiles" "$keystore_password_files"
append_option "--KeyStore.Passwords" "$keystore_passwords"
append_option "--KeyStore.SymmetricEncrypterBlockSize" "$keystore_symmetric_encrypter_block_size"
append_option "--KeyStore.SymmetricEncrypterKeySize" "$keystore_symmetric_encrypter_key_size"
append_option "--KeyStore.TestNodeKey" "$keystore_test_node_key"
append_option "--KeyStore.UnlockAccounts" "$keystore_unlock_accounts"
append_option "--Merge.BuilderRelayUrl" "$merge_builder_relay_url"
append_option "--Merge.CollectionsPerDecommit" "$merge_collections_per_decommit"
append_option "--Merge.CompactMemory" "$merge_compact_memory"
append_option   "--Merge.Enabled" "$merge_enabled"
append_option "--Merge.FinalTotalDifficulty" "$merge_final_total_difficulty"
append_option "--Merge.NewPayloadTimeout" "$merge_new_payload_timeout"
append_option   "--Merge.PrioritizeBlockLatency" "$merge_prioritize_block_latency"
append_option "--Merge.SecondsPerSlot" "$merge_seconds_per_slot"
append_option   "--Merge.SimulateBlockProduction" "$merge_simulate_block_production"
append_option "--Merge.SweepMemory" "$merge_sweep_memory"
append_option "--Merge.TerminalBlockHash" "$merge_terminal_block_hash"
append_option "--Merge.TerminalBlockNumber" "$merge_terminal_block_number"
append_option "--Merge.TerminalTotalDifficulty" "$merge_terminal_total_difficulty"
append_option   "--Metrics.CountersEnabled" "$metrics_counters_enabled"
append_option   "--Metrics.EnableDbSizeMetrics" "$metrics_enable_db_size_metrics"
append_option   "--Metrics.Enabled" "$metrics_enabled"
append_option "--Metrics.ExposeHost" "$metrics_expose_host"
append_option "--Metrics.ExposePort" "$metrics_expose_port"
append_option "--Metrics.IntervalSeconds" "$metrics_interval_seconds"
append_option "--Metrics.NodeName" "$metrics_node_name"
append_option "--Metrics.PushGatewayUrl" "$metrics_push_gateway_url"
append_option   "--Mining.Enabled" "$mining_enabled"
append_option "--Mining.ExtraData" "$mining_extra_data"
append_option "--Mining.MinGasPrice" "$mining_min_gas_price"
append_option   "--Mining.RandomizedBlocks" "$mining_randomized_blocks"
append_option "--Mining.Signer" "$mining_signer"
append_option "--Mining.TargetBlockGasLimit" "$mining_target_block_gas_limit"
append_option "--Network.ActivePeersMaxCount" "$network_active_peers_max_count"
append_option "--Network.Bootnodes" "$network_bootnodes"
append_option "--Network.ClientIdMatcher" "$network_client_id_matcher"
append_option "--Network.ConnectTimeoutMs" "$network_connect_timeout_ms"
append_option   "--Network.DiagTracerEnabled" "$network_diag_tracer_enabled"
append_option   "--Network.DisableDiscV4DnsFeeder" "$network_disable_discv4_dns_feeder"
append_option "--Network.DiscoveryDns" "$network_discovery_dns"
append_option "--Network.DiscoveryPort" "$network_discovery_port"
append_option   "--Network.EnableUPnP" "$network_enable_upnp"
append_option "--Network.ExternalIp" "$network_external_ip"
append_option "--Network.LocalIp" "$network_local_ip"
append_option "--Network.MaxActivePeers" "$network_max_active_peers"
append_option "--Network.MaxNettyArenaCount" "$network_max_netty_arena_count"
append_option "--Network.MaxOutgoingConnectPerSec" "$network_max_outgoing_connect_per_sec"
append_option "--Network.NettyArenaOrder" "$network_netty_arena_order"
append_option "--Network.NumConcurrentOutgoingConnects" "$network_num_concurrent_outgoing_connects"
append_option   "--Network.OnlyStaticPeers" "$network_only_static_peers"
append_option "--Network.P2PPort" "$network_p2p_port"
append_option "--Network.PriorityPeersMaxCount" "$network_priority_peers_max_count"
append_option "--Network.ProcessingThreadCount" "$network_processing_thread_count"
append_option "--Network.SimulateSendLatencyMs" "$network_simulate_send_latency_ms"
append_option "--Network.StaticPeers" "$network_static_peers"
append_option "--Optimism.SequencerUrl" "$optimism_sequencer_url"
append_option "--Plugin.PluginOrder" "$plugin_plugin_order"
append_option   "--Pruning.AvailableSpaceCheckEnabled" "$pruning_available_space_check_enabled"
append_option "--Pruning.CacheMb" "$pruning_cache_mb"
append_option   "--Pruning.Enabled" "$pruning_enabled"
append_option "--Pruning.FullPruningCompletionBehavior" "$pruning_full_pruning_completion_behavior"
append_option   "--Pruning.FullPruningDisableLowPriorityWrites" "$pruning_full_pruning_disable_low_priority_writes"
append_option "--Pruning.FullPruningMaxDegreeOfParallelism" "$pruning_full_pruning_max_degree_of_parallelism"
append_option "--Pruning.FullPruningMemoryBudgetMb" "$pruning_full_pruning_memory_budget_mb"
append_option "--Pruning.FullPruningMinimumDelayHours" "$pruning_full_pruning_minimum_delay_hours"
append_option "--Pruning.FullPruningThresholdMb" "$pruning_full_pruning_threshold_mb"
append_option "--Pruning.FullPruningTrigger" "$pruning_full_pruning_trigger"
append_option "--Pruning.Mode" "$pruning_mode"
append_option "--Pruning.PersistenceInterval" "$pruning_persistence_interval"
append_option "--Pruning.PruningBoundary" "$pruning_pruning_boundary"
append_option "--Pruning.TrackedPastKeyCountMemoryRatio" "$pruning_tracked_past_key_count_memory_ratio"
append_option   "--Receipt.CompactReceiptStore" "$receipt_compact_receipt_store"
append_option   "--Receipt.CompactTxIndex" "$receipt_compact_tx_index"
append_option   "--Receipt.ForceReceiptsMigration" "$receipt_force_receipts_migration"
append_option "--Receipt.MaxBlockDepth" "$receipt_max_block_depth"
append_option   "--Receipt.ReceiptsMigration" "$receipt_receipts_migration"
append_option "--Receipt.ReceiptsMigrationDegreeOfParallelism" "$receipt_receipts_migration_degree_of_parallelism"
append_option   "--Receipt.StoreReceipts" "$receipt_store_receipts"
append_option "--Receipt.TxLookupLimit" "$receipt_tx_lookup_limit"
append_option "--Seq.ApiKey" "$seq_api_key"
append_option "--Seq.MinLevel" "$seq_min_level"
append_option "--Seq.ServerUrl" "$seq_server_url"
append_option "--Snapshot.Checksum" "$snapshot_checksum"
append_option "--Snapshot.DownloadUrl" "$snapshot_download_url"
append_option   "--Snapshot.Enabled" "$snapshot_enabled"
append_option "--Snapshot.SnapshotDirectory" "$snapshot_snapshot_directory"
append_option "--Snapshot.SnapshotFileName" "$snapshot_snapshot_file_name"
append_option "--Sync.AncientBodiesBarrier" "$sync_ancient_bodies_barrier"
append_option "--Sync.AncientReceiptsBarrier" "$sync_ancient_receipts_barrier"
append_option "--Sync.BlocksDbTuneDbMode" "$sync_blocks_db_tune_db_mode"
append_option   "--Sync.DownloadBodiesInFastSync" "$sync_download_bodies_in_fast_sync"
append_option   "--Sync.DownloadHeadersInFastSync" "$sync_download_headers_in_fast_sync"
append_option   "--Sync.DownloadReceiptsInFastSync" "$sync_download_receipts_in_fast_sync"
append_option   "--Sync.ExitOnSynced" "$sync_exit_on_synced"
append_option "--Sync.ExitOnSyncedWaitTimeSec" "$sync_exit_on_synced_wait_time_sec"
append_option   "--Sync.FastBlocks" "$sync_fast_blocks"
append_option   "--Sync.FastSync" "$sync_fast_sync"
append_option "--Sync.FastSyncCatchUpHeightDelta" "$sync_fast_sync_catch_up_height_delta"
append_option   "--Sync.FixReceipts" "$sync_fix_receipts"
append_option   "--Sync.FixTotalDifficulty" "$sync_fix_total_difficulty"
append_option "--Sync.FixTotalDifficultyLastBlock" "$sync_fix_total_difficulty_last_block"
append_option "--Sync.FixTotalDifficultyStartingBlock" "$sync_fix_total_difficulty_starting_block"
append_option "--Sync.MallocTrimIntervalSec" "$sync_malloc_trim_interval_sec"
append_option "--Sync.MaxAttemptsToUpdatePivot" "$sync_max_attempts_to_update_pivot"
append_option "--Sync.MaxProcessingThreads" "$sync_max_processing_threads"
append_option "--Sync.MultiSyncModeSelectorLoopTimerMs" "$sync_multi_sync_mode_selector_loop_timer_ms"
append_option   "--Sync.NetworkingEnabled" "$sync_networking_enabled"
append_option   "--Sync.NonValidatorNode" "$sync_non_validator_node"
append_option "--Sync.PivotHash" "$sync_pivot_hash"
append_option "--Sync.PivotNumber" "$sync_pivot_number"
append_option "--Sync.PivotTotalDifficulty" "$sync_pivot_total_difficulty"
append_option   "--Sync.SnapServingEnabled" "$sync_snap_serving_enabled"
append_option   "--Sync.SnapSync" "$sync_snap_sync"
append_option "--Sync.SnapSyncAccountRangePartitionCount" "$sync_snap_sync_account_range_partition_count"
append_option   "--Sync.StrictMode" "$sync_strict_mode"
append_option   "--Sync.SynchronizationEnabled" "$sync_synchronization_enabled"
append_option   "--Sync.TrieHealing" "$sync_trie_healing"
append_option "--Sync.TuneDbMode" "$sync_tune_db_mode"
append_option   "--Sync.UseGethLimitsInFastBlocks" "$sync_use_geth_limits_in_fast_blocks"
append_option "--TraceStore.BlocksToKeep" "$trace_store_blocks_to_keep"
append_option "--TraceStore.DeserializationParallelization" "$trace_store_deserialization_parallelization"
append_option   "--TraceStore.Enabled" "$trace_store_enabled"
append_option "--TraceStore.MaxDepth" "$trace_store_max_depth"
append_option "--TraceStore.TraceTypes" "$trace_store_trace_types"
append_option   "--TraceStore.VerifySerialized" "$trace_store_verify_serialized"
append_option "--TxPool.BlobCacheSize" "$tx_pool_blob_cache_size"
append_option "--TxPool.BlobsSupport" "$tx_pool_blobs_support"
append_option "--TxPool.GasLimit" "$tx_pool_gas_limit"
append_option "--TxPool.HashCacheSize" "$tx_pool_hash_cache_size"
append_option "--TxPool.InMemoryBlobPoolSize" "$tx_pool_in_memory_blob_pool_size"
append_option "--TxPool.MaxPendingBlobTxsPerSender" "$tx_pool_max_pending_blob_txs_per_sender"
append_option "--TxPool.MaxPendingTxsPerSender" "$tx_pool_max_pending_txs_per_sender"
append_option "--TxPool.MinBaseFeeThreshold" "$tx_pool_min_base_fee_threshold"
append_option "--TxPool.PeerNotificationThreshold" "$tx_pool_peer_notification_threshold"
append_option "--TxPool.PersistentBlobStorageSize" "$tx_pool_persistent_blob_storage_size"
append_option "--TxPool.ReportMinutes" "$tx_pool_report_minutes"
append_option "--TxPool.Size" "$tx_pool_size"
append_option "--Wallet.DevAccounts" "$wallet_dev_accounts"



echo "Using Options: nethermind $OPTIONS"

# CI problem again, with cache
exec /usr/lib/eth-node-nethermind/bin/Nethermind.Runner/release/nethermind $OPTIONS