#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path_beacon_chain(){
  output="$(which beacon-chain)"
  assertEquals "/usr/bin/beacon-chain" "$output"
}

test_beacon_chain_invocation(){
  output="$(beacon-chain --version)"
  echo "$output"
  # checked against https://github.com/prysmaticlabs/prysm/releases/download/v4.1.1/beacon-chain-v4.1.1-linux-amd64
  # Note build at information is static, to achieve reproducible builds
  assertEquals "$output" "beacon-chain version Prysm/v5.3.1/863eee7b40618e3af4cfff955a78b3cc66d63f9e. Built at: 2025-03-14 11:39:13+00:00" 
}



. shunit2