#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.3.2
Commit SHA: 802a1c7bd6fc3b1c5e051048ca7f96fedef838d3
Build Timestamp: 2025-03-18T07:25Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

