[package_fields]
spec_file = "eth-node-nimbus-eth2.sss"
package_name = "eth-node-nimbus-eth2"
version_number = "24.10.0"
revision_number = "1"
homepage = "https://github.com/status-im/nimbus-eth2"

[package_type]
# virtual | git | default
package_type = "git"
git_url = "https://github.com/status-im/nimbus-eth2.git"
git_tag = "v24.10.0"
submodules = [
        { "commit" = "73fbb29019c19887235c1da456cfbfd5b4835184", "path" = "vendor/EIPs" },
        { "commit" = "7721c955b522f4893265bb36a6de4f8edef8b54b", "path" = "vendor/NimYAML" },
        { "commit" = "0e085cb606e78a495ce8014f9350931bc360e663", "path" = "vendor/gnosis-chain-configs" },
        { "commit" = "37eaaf80084489af9459836c03c6e24b9e431c2a", "path" = "vendor/holesky" },
        { "commit" = "f6b7882618a5ad2c1d2731ae35e5d16a660d5bb7", "path" = "vendor/mainnet" },
        { "commit" = "953a795b96d73a7401e7a1041587da9ffe6d78f6", "path" = "vendor/nim-bearssl" },
        { "commit" = "de2d3c79264bba18dbea469c8c5c4b3bb3c8bc55", "path" = "vendor/nim-blscurve" },
        { "commit" = "81a4a7a360c78be9c80c8f735c76b6d4a1517304", "path" = "vendor/nim-chronicles" },
        { "commit" = "c04576d829b8a0a1b12baaa8bc92037501b3a4a0", "path" = "vendor/nim-chronos" },
        { "commit" = "9bf293e5d29294848a9d2d79363d971d2abe8254", "path" = "vendor/nim-confutils" },
        { "commit" = "66297c5c0a8c22ec3f16c899e902d79aa00df575", "path" = "vendor/nim-eth" },
        { "commit" = "93996ec0865765d94b1f72825bd98a5aef215a12", "path" = "vendor/nim-eth2-scenarios" },
        { "commit" = "c246d00eaa7d6f52019464b37da510a8be23e939", "path" = "vendor/nim-faststreams" },
        { "commit" = "8bb1acbaa4b86eb866145b0d468eff64a57d1897", "path" = "vendor/nim-http-utils" },
        { "commit" = "0408795be95c00d75e96eaef6eae8a9c734014f5", "path" = "vendor/nim-json-rpc" },
        { "commit" = "6eadb6e939ffa7882ff5437033c11a9464d3385c", "path" = "vendor/nim-json-serialization" },
        { "commit" = "abef457e17c56901fd038bb1a7e11dfd5a4f919a", "path" = "vendor/nim-kzg4844" },
        { "commit" = "31d8d5c170441f11a730582ef353e506a3780b7a", "path" = "vendor/nim-libbacktrace" },
        { "commit" = "09fe199b6bee6c3d0cc0e8750e67bbc0d52da138", "path" = "vendor/nim-libp2p" },
        { "commit" = "cacfdc12454a0804c65112b9f4f50d1375208dcd", "path" = "vendor/nim-metrics" },
        { "commit" = "c35304151ea39077330f225e3837450990d55e48", "path" = "vendor/nim-minilru" },
        { "commit" = "5e4059746e9095e1731b02eeaecd62a70fbe664d", "path" = "vendor/nim-nat-traversal" },
        { "commit" = "08caa2a4da40580ed7fe3ce723b3f7feabcca8e5", "path" = "vendor/nim-normalize" },
        { "commit" = "bd410a26e0da62fdcf56d2be17bd53d84868a457", "path" = "vendor/nim-presto" },
        { "commit" = "71d404b314479a6205bfd050f4fe5fe49cdafc69", "path" = "vendor/nim-results" },
        { "commit" = "0706e2c350266017dcd663ff2727eb2b03d2fa44", "path" = "vendor/nim-secp256k1" },
        { "commit" = "08055d72f3ce0b29e799c191713e0ca2e903fe71", "path" = "vendor/nim-serialization" },
        { "commit" = "590edb152071bca4901bcbe689fc0856efd8c4e7", "path" = "vendor/nim-snappy" },
        { "commit" = "acd3c327433784226b412757bdb5455b5be04c55", "path" = "vendor/nim-sqlite3-abi" },
        { "commit" = "3397088499cefc2e7aa5e73a56ad2d5b0f091735", "path" = "vendor/nim-ssz-serialization" },
        { "commit" = "a6e198132097fb544d04959aeb3b839e1408f942", "path" = "vendor/nim-stew" },
        { "commit" = "3236fa68394f1e3a06e2bc34218aacdd2d675923", "path" = "vendor/nim-stint" },
        { "commit" = "66585e2e960b7695e48ea60377fb3aeac96406e8", "path" = "vendor/nim-taskpools" },
        { "commit" = "4d37244f9f5e1acd8592a4ceb5c3fc47bc160181", "path" = "vendor/nim-testutils" },
        { "commit" = "fea85b27f0badcf617033ca1bc05444b5fd8aa7a", "path" = "vendor/nim-toml-serialization" },
        { "commit" = "15c5e25e2a49a924bc97647481ff50125bba2c76", "path" = "vendor/nim-unicodedb" },
        { "commit" = "845b6af28b9f68f02d320e03ad18eccccea7ddb9", "path" = "vendor/nim-unittest2" },
        { "commit" = "c76ddefea96e7763c3cc5b28ec5cbac1adefc4e7", "path" = "vendor/nim-web3" },
        { "commit" = "179f81dedaddb5ba8d02534ccc8b7a8335981f49", "path" = "vendor/nim-websock" },
        { "commit" = "91cf360b1aeb2e0c753ff8bac6de22a41c5ed8cd", "path" = "vendor/nim-zlib" },
        { "commit" = "f31e4bd8fef867799bc42e47b073925a281349f3", "path" = "vendor/nim-zxcvbn" },
        { "commit" = "dff3634b5d843f9b63425086f1b13245e26b6177", "path" = "vendor/nimbus-benchmarking" },
        { "commit" = "4afb0526629f51aef4c124368365ebe90a782d37", "path" = "vendor/nimbus-build-system" },
        { "commit" = "ce9945b1b159d4c9b628f8c4cd2d262964692810", "path" = "vendor/nimbus-security-resources" },
        { "commit" = "dc07e3058c6904eef965394493b6ea99aa2adefc", "path" = "vendor/nimcrypto" },
        { "commit" = "f2c219a93c4491cee3d90c18f2f8e82aed850eab", "path" = "vendor/sepolia" }
        ]


[package_type.language_env]
language_env = "nim"
nim_version = "2.0.6" # according to docs, downgrade nim version to this version
nim_binary_url = "https://nim-lang.org/download/nim-2.0.6-linux_x64.tar.xz"
nim_version_checksum = "4613c18f6c70d14f7fcbcb0c644425699862902ec64d7b785ededaf161815cdc nim-2.0.6-linux_x64.tar.xz"


[build_env]
codename = "bookworm"
arch = "amd64"
pkg_builder_version = "0.2.8"
debcrafter_version = "2711b53"
run_lintian = true
run_piuparts = true
run_autopkgtest = true
lintian_version = "2.116.3"
piuparts_version = "1.1.7"
autopkgtest_version = "5.28"
sbuild_version = "0.85.6"
# package directory
workdir = "~/.pkg-builder/packages/bookworm"
