#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version:1.0.2
Commit SHA: ffb44e6245eebd0144e8ae62f4f39203f2ea2e5f
Build Timestamp: 2024-07-17T19:31Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

