#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.1.1
Commit SHA: 15c230bac20e2b1b3532c8b0d470e815fbc0cc22
Build Timestamp: 2024-11-06T07:30Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

