[verify]
package_hash=[
    # { hash="c7fded18bcd75c51bfd4fd87c6221c281ea36703", name= "eth-node-nimbus-eth2_24.5.1-1.dsc"},
    # disable as it fails day by day, we don't care about this, until the other hashes are the same
    # { hash="f0773b315ea03acaaca3d3959877e4d02758a5fd", name= "eth-node-nimbus-eth2_24.3.0.orig.tar.gz"},
    { hash="dfa2face0523d1b7c385fc38e9b8867e0816f429", name= "eth-node-nimbus-eth2_25.5.0-1.debian.tar.xz"},
    { hash="6d78deae6031c12d65bf5ae8d581689aada4b7ac", name= "eth-node-nimbus-eth2_25.5.0-1_amd64.deb"},
]
