#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.1.3
Commit SHA: d97449dae495a2243000078fa30b3b164ef5891b
Build Timestamp: 2024-12-11T09:42Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

