[package_fields]
spec_file = "eth-node-prysm.sss"
package_name = "eth-node-prysm"
version_number = "5.2.0"
revision_number = "1"
homepage="https://github.com/prysmaticlabs/prysm"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/prysmaticlabs/prysm/archive/refs/tags/v5.2.0.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "e3b553ee6da6856184bb720ef580c2d28a320983f2028e61cdb3a324e209e0a6"

[package_type.language_env]
language_env = "go"
go_version = "1.22.2"
go_binary_url = "https://go.dev/dl/go1.22.2.linux-amd64.tar.gz"
go_binary_checksum = "5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17"

[package_type.language_env.bazelisk]
bazelisk_version="1.18.0"

[build_env]
codename="noble numbat"
arch = "amd64"
pkg_builder_version="0.2.8"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/noble"
