#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.0.7
Commit SHA: 75b7172cf77eb4fd65fe1a6924f75066fb09fcd1
Build Timestamp: 2024-09-20T09:05Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

