#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.1.2
Commit SHA: 496bf0bf715f0a1fafc198f8d72ccd71913d1a40
Build Timestamp: 2024-11-19T17:46Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

