#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path_beacon_chain(){
  output="$(which beacon-chain)"
  assertEquals "/usr/bin/beacon-chain" "$output"
}

test_beacon_chain_invocation(){
  output="$(beacon-chain --version)"
  echo "$output"
  # checked against https://github.com/prysmaticlabs/prysm/releases/download/v4.1.1/beacon-chain-v4.1.1-linux-amd64
  # Note build at information is static, to achieve reproducible builds
  assertEquals "$output" "beacon-chain version Prysm/v6.0.4/91b44360fcd74bad41f38b79bb3b05094408a2d0. Built at: 2025-06-06 09:56:44+00:00" 
}



. shunit2