#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path_beacon_chain(){
  output="$(which beacon-chain)"
  assertEquals "/usr/bin/beacon-chain" "$output"
}

test_beacon_chain_invocation(){
  output="$(beacon-chain --version)"
  echo "$output"
  # checked against https://github.com/prysmaticlabs/prysm/releases/download/v4.1.1/beacon-chain-v4.1.1-linux-amd64
  # Note build at information is static, to achieve reproducible builds
  assertEquals "$output" "beacon-chain version Prysm/v6.0.2/2ec1ef53dcb114da22698e8ccd9bc1e3aa8e3870. Built at: 2025-05-13 08:06:19+00:00" 
}



. shunit2