#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.3.10
Commit SHA: b36fc954d26258ac727b5cc13b771524411e1001
Build Timestamp: 2025-04-16T06:53Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

