[package_fields]
spec_file = "eth-node-geth.sss"
package_name = "eth-node-geth"
version_number = "1.16.0"
revision_number = "1"
homepage="https://github.com/ethereum/go-ethereum"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/ethereum/go-ethereum/archive/refs/tags/v1.16.0.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "166333b7d6595ce339c02e7b580b8dda9a7481a3d53cdcab3b5d401738ab0a14"

[package_type.language_env]
language_env = "go"
go_version = "1.24.2"
go_binary_url = "https://go.dev/dl/go1.24.2.linux-amd64.tar.gz"
go_binary_checksum = "68097bd680839cbc9d464a0edce4f7c333975e27a90246890e9f1078c7e702ad"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.3.1"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/bookworm"
