#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which besu)"
  assertEquals "/usr/bin/besu" "$output"
}

test_invocation(){
  output="$(besu --version)"
  assertEquals "besu/v23.10.1/linux-x86_64/oracle-java-17" "$output"
}

. shunit2