HOME := /home/debian
WORK_DIR := /tmp/eth-pkg
SHELL := /bin/bash
CODENAME := bookworm
ARCH:=amd64

CLIENT := besu
CLIENT_FULL_NAME := eth-node-$(CLIENT)
VERSION_NUMBER := $(shell dpkg-parsechangelog -l $(CLIENT_FULL_NAME).changelog -S Version 2>/dev/null | sed 's/-.*//')
PACKAGE_NAME := $(CLIENT_FULL_NAME)-$(VERSION_NUMBER)
TARBALL_URL := https://github.com/hyperledger/besu/archive/refs/tags/$(VERSION_NUMBER).tar.gz
GIT_SOURCE := https://github.com/hyperledger/besu.git

IS_VIRTUAL_PACKAGE := 

