#!/bin/bash
set -e

. /usr/share/debconf/confmodule

declare -A CONFIG

adduser --system --quiet --group --home "/var/lib/eth-node-erigon-service-sepolia" eth-node-erigon-service-sepolia

usermod -a -G eth-node-erigon-sepolia eth-node-erigon-service-sepolia
db_get eth-node-erigon-service-sepolia/datadir
CONFIG["eth-node-erigon-service-sepolia/datadir"]="$RET"
db_get eth-node-erigon-service-sepolia/chain
CONFIG["eth-node-erigon-service-sepolia/chain"]="$RET"
db_get eth-node-erigon-service-sepolia/port
CONFIG["eth-node-erigon-service-sepolia/port"]="$RET"
db_get eth-node-erigon-service-sepolia/http.port
CONFIG["eth-node-erigon-service-sepolia/http.port"]="$RET"
db_get eth-node-erigon-service-sepolia/authrpc.port
CONFIG["eth-node-erigon-service-sepolia/authrpc.port"]="$RET"
db_get eth-node-erigon-service-sepolia/torrent.port
CONFIG["eth-node-erigon-service-sepolia/torrent.port"]="$RET"
db_get eth-node-erigon-service-sepolia/private.api.addr
CONFIG["eth-node-erigon-service-sepolia/private.api.addr"]="$RET"
db_get eth-node-erigon-service-sepolia/http
CONFIG["eth-node-erigon-service-sepolia/http"]="$RET"
db_get eth-node-erigon-service-sepolia/ws
CONFIG["eth-node-erigon-service-sepolia/ws"]="$RET"
db_get eth-node-erigon-service-sepolia/http.api
CONFIG["eth-node-erigon-service-sepolia/http.api"]="$RET"
db_get eth-node-erigon-service-sepolia/authrpc.jwtsecret
CONFIG["eth-node-erigon-service-sepolia/authrpc.jwtsecret"]="$RET"
mkdir -p "`dirname "/etc/eth-node-erigon-service-sepolia/config.toml"`"
echo -n > "/etc/eth-node-erigon-service-sepolia/config.toml"
echo '# Automtically generated - DO NOT MODIFY!' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
chgrp "eth-node-erigon-service-sepolia" "/etc/eth-node-erigon-service-sepolia/config.toml"
chmod 640 /etc/eth-node-erigon-service-sepolia/config.toml
RET="${CONFIG[eth-node-erigon-service-sepolia/authrpc.jwtsecret]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
echo -n "authrpc.jwtsecret=\"" >> "/etc/eth-node-erigon-service-sepolia/config.toml"
if [ $(cat << EOF | wc -c
$RET
EOF
) -gt 1 ]; then
cat << EOF | perl -pe 'chomp if eof' | sed -e 's/\\/\\\\/' -e 's/"/\\"/' | awk 1 ORS='\n' | sed 's/$/"/' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
$RET
EOF
else
echo '"' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
fi

RET="${CONFIG[eth-node-erigon-service-sepolia/authrpc.port]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
cat << EOF >> "/etc/eth-node-erigon-service-sepolia/config.toml"
authrpc.port = $RET
EOF

RET="${CONFIG[eth-node-erigon-service-sepolia/chain]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
echo -n "chain=\"" >> "/etc/eth-node-erigon-service-sepolia/config.toml"
if [ $(cat << EOF | wc -c
$RET
EOF
) -gt 1 ]; then
cat << EOF | perl -pe 'chomp if eof' | sed -e 's/\\/\\\\/' -e 's/"/\\"/' | awk 1 ORS='\n' | sed 's/$/"/' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
$RET
EOF
else
echo '"' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
fi

RET="${CONFIG[eth-node-erigon-service-sepolia/datadir]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
echo -n "datadir=\"" >> "/etc/eth-node-erigon-service-sepolia/config.toml"
if [ $(cat << EOF | wc -c
$RET
EOF
) -gt 1 ]; then
cat << EOF | perl -pe 'chomp if eof' | sed -e 's/\\/\\\\/' -e 's/"/\\"/' | awk 1 ORS='\n' | sed 's/$/"/' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
$RET
EOF
else
echo '"' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
fi

RET="${CONFIG[eth-node-erigon-service-sepolia/http]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
cat << EOF >> "/etc/eth-node-erigon-service-sepolia/config.toml"
http = $RET
EOF

RET="${CONFIG[eth-node-erigon-service-sepolia/http.api]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
echo -n "http.api=\"" >> "/etc/eth-node-erigon-service-sepolia/config.toml"
if [ $(cat << EOF | wc -c
$RET
EOF
) -gt 1 ]; then
cat << EOF | perl -pe 'chomp if eof' | sed -e 's/\\/\\\\/' -e 's/"/\\"/' | awk 1 ORS='\n' | sed 's/$/"/' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
$RET
EOF
else
echo '"' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
fi

RET="${CONFIG[eth-node-erigon-service-sepolia/http.port]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
cat << EOF >> "/etc/eth-node-erigon-service-sepolia/config.toml"
http.port = $RET
EOF

RET="${CONFIG[eth-node-erigon-service-sepolia/port]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
cat << EOF >> "/etc/eth-node-erigon-service-sepolia/config.toml"
port = $RET
EOF

RET="${CONFIG[eth-node-erigon-service-sepolia/private.api.addr]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
echo -n "private.api.addr=\"" >> "/etc/eth-node-erigon-service-sepolia/config.toml"
if [ $(cat << EOF | wc -c
$RET
EOF
) -gt 1 ]; then
cat << EOF | perl -pe 'chomp if eof' | sed -e 's/\\/\\\\/' -e 's/"/\\"/' | awk 1 ORS='\n' | sed 's/$/"/' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
$RET
EOF
else
echo '"' >> "/etc/eth-node-erigon-service-sepolia/config.toml"
fi

RET="${CONFIG[eth-node-erigon-service-sepolia/torrent.port]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
cat << EOF >> "/etc/eth-node-erigon-service-sepolia/config.toml"
torrent.port = $RET
EOF

RET="${CONFIG[eth-node-erigon-service-sepolia/ws]}"
echo >> "/etc/eth-node-erigon-service-sepolia/config.toml"
cat << EOF >> "/etc/eth-node-erigon-service-sepolia/config.toml"
ws = $RET
EOF

MAINTSCRIPT_ACTION="$1" MAINTSCRIPT_VERSION="$2" 'bash' '/usr/lib/eth-node-erigon/bin/fix-service-config.sh' 'sepolia'
dpkg-trigger --no-await "`realpath "/etc/eth-node-erigon-service-sepolia/config.toml"`"
if [ "$1" = triggered -a "$service_was_running" '!=' 0 ];
then
	deb-systemd-invoke restart eth-node-erigon-service-sepolia
fi

if [ "$1" '!=' triggered ];
then
	dpkg-trigger eth-node-erigon-service-sepolia-config-changed

fi
#DEBHELPER#

exit 0
