#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path_beacon_chain(){
  output="$(which beacon-chain)"
  assertEquals "/usr/bin/beacon-chain" "$output"
}

test_beacon_chain_invocation(){
  output="$(beacon-chain --version)"
  echo "$output"
  # checked against https://github.com/prysmaticlabs/prysm/releases/download/v4.1.1/beacon-chain-v4.1.1-linux-amd64
  # Note build at information is static, to achieve reproducible builds
  assertEquals "$output" "beacon-chain version Prysm/v6.0.3/eafef8c7c803f5a63755a9a63377c3bd6459aa41. Built at: 2025-05-22 09:45:15+00:00" 
}



. shunit2