#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.5.1
Commit SHA: dbe7ee9c21392f360ff01f6307480f5d7dd73a3a
Build Timestamp: 2025-07-09T11:24Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

