#!/bin/bash
set -e

. /usr/share/debconf/confmodule

declare -A CONFIG

adduser --system --quiet --group eth-node-mainnet-service-nimbus-eth2 
mkdir -p /var/lib/eth-node-mainnet/nimbus-eth2
chown eth-node-mainnet-service-nimbus-eth2:eth-node-mainnet-service-nimbus-eth2 /var/lib/eth-node-mainnet/nimbus-eth2 

if [ "$1" = triggered -a "$service_was_running" '!=' 0 ];
then
	deb-systemd-invoke restart eth-node-mainnet-service-nimbus-eth2
fi

if [ "$1" '!=' triggered ];
then
	dpkg-trigger eth-node-mainnet-service-nimbus-eth2-config-changed

fi
#DEBHELPER#

exit 0
