#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.3.4
Commit SHA: 90c514ca818a36eb8cd36866156c26a4221e9c4a
Build Timestamp: 2025-03-22T08:08Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

