#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which prysm)"
  assertEquals "/usr/bin/prysm" "$output"
}

test_invocation(){
  output="$(prysm --version)"
  # TODO version should not be unknown 
  assertContains "beacon-chain version Prysm/Unknown/" "$output"
}

test_binary_in_path_nimbus_eth2(){
  output="$(which beacon-chain)"
  assertEquals "/usr/bin/nimbus-eth2" "$output"
}

test_invocation(){
  output="$(beacon-chain --version)"
  assertContains "beacon-chain version Prysm/Unknown/" "$output"
}

test_that_links_are_same(){
  output1="$(beacon-chain --version)"
  output2="$(prysm --version)"
  assertEquals "$output1" "$output2"
}

. shunit2