#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path_beacon_chain(){
  output="$(which beacon-chain)"
  assertEquals "/usr/bin/beacon-chain" "$output"
}

test_beacon_chain_invocation(){
  output="$(beacon-chain --version)"
  echo "$output"
  # checked against https://github.com/prysmaticlabs/prysm/releases/download/v4.1.1/beacon-chain-v4.1.1-linux-amd64
  assertContains "$output" "beacon-chain version Prysm/v4.1.1/bc9151d647e70cf5e0b6dbcee01998c430a96cb5" 
}



. shunit2