#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path_beacon_chain(){
  output="$(which beacon-chain)"
  assertEquals "/usr/bin/beacon-chain" "$output"
}

test_beacon_chain_invocation(){
  output="$(beacon-chain --version)"
  output=$(echo "$output" | cut -d'/' -f1)
  assertContains "beacon-chain version Prysm" "$output"
}



. shunit2