#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.4.8
Commit SHA: 127595e23079de2c494048d0821ea1f1107eb624
Build Timestamp: 2025-06-05T05:50Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

