[verify]
package_hash=[
    # { hash="c7fded18bcd75c51bfd4fd87c6221c281ea36703", name= "eth-node-nimbus-eth2_24.5.1-1.dsc"},
    # disable as it fails day by day, we don't care about this, until the other hashes are the same
    # { hash="f0773b315ea03acaaca3d3959877e4d02758a5fd", name= "eth-node-nimbus-eth2_24.3.0.orig.tar.gz"},
    { hash="66b0258f260ac92d0ca31884d69db66c6749ee8c", name= "eth-node-nimbus-eth2_25.4.0-1.debian.tar.xz"},
    { hash="f8d93b21e0e144811c7b6db4bf237fc2e44e3565", name= "eth-node-nimbus-eth2_25.4.0-1_amd64.deb"},
]
