#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.5.0
Commit SHA: 61e38f9af154fe91e776d8f5e449d20a1571e8cf
Build Timestamp: 2025-06-26T16:24Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

