[verify]
package_hash=[
    # { hash="8acafcede1991021c60b6bda87134f17e22024ba", name= "eth-node-nimbus-eth2_24.6.0-1.dsc"},
    # disable as it fails day by day, we don't care about this, until the other hashes are the same
    # { hash="f0773b315ea03acaaca3d3959877e4d02758a5fd", name= "eth-node-nimbus-eth2_24.3.0.orig.tar.gz"},
    { hash="1417e0bd8acafd8546328f5770e2b2a62a87480d", name= "eth-node-nimbus-eth2_25.2.0-1.debian.tar.xz"},
    { hash="429c6237c495764c73d8663d0de2423efa784f9a", name= "eth-node-nimbus-eth2_25.2.0-1_amd64.deb"},
]
