#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which nimbus_beacon_node)"
  assertEquals "/usr/bin/nimbus_beacon_node" "$output"
}

test_invocation_run_beacon_node(){
  output="$(nimbus_beacon_node --version)"
  assertContains "Nimbus beacon node v24.3.0-" "$output"
  assertContains "Copyright (c) 2019-2024 Status Research & Development GmbH" "$output"
  assertContains "eth2 specification v1.4.0" "$output"
  assertContains "Nim Compiler Version 2.0.2 [Linux: amd64]" "$output"
}

. shunit2