#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which erigon)"
  assertEquals "/usr/bin/erigon" "$output"
}

test_invocation(){
  output="$(erigon --version)"
  echo "$output"
  # checked againts https://github.com/ledgerwatch/erigon/releases/download/v2.53.2/erigon_2.53.2_linux_amd64.tar.gz
  assertEquals "erigon version 2.61.0" "$output"
}

. shunit2