[package_fields]
spec_file = "eth2-testnet-genesis.sss"
package_name = "eth2-testnet-genesis"
version_number = "0.12.0"
revision_number = "1"
homepage="https://github.com/protolambda/eth2-testnet-genesis"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/protolambda/eth2-testnet-genesis/archive/refs/tags/v0.10.0.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "0c43daaa78161f7022bca59fbb363f66d6dd5fddc6c1dc619894d7bcf107cd25"

[package_type.language_env]
language_env = "go"
go_version = "1.22.2"
go_binary_url = "https://go.dev/dl/go1.22.2.linux-amd64.tar.gz"
go_binary_checksum = "5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17"

[build_env]
codename="noble numbat"
arch = "amd64"
pkg_builder_version="0.2.11"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/noble"
