[verify]
package_hash=[
    { hash="2aae2b916855f3e8c9598f02eb2ae881f661b99d", name= "ethereum-genesis-generator_<CLIENT_VERSION>-<CLIENT_REVISION>.dsc"},
    { hash="00bdd00bf8cf263dda45fbcd385340d55836b4ab", name= "ethereum-genesis-generator_<CLIENT_VERSION>.orig.tar.gz"},
    { hash="84837a918454c880e63bde6928f582e1a66180c7", name= "ethereum-genesis-generator_<CLIENT_VERSION>-<CLIENT_REVISION>.debian.tar.xz"},
    { hash="195cc72db45dbfc63d175e33cf7129acde1e8e83", name= "ethereum-genesis-generator_<CLIENT_VERSION>-<CLIENT_REVISION>_amd64.deb"},
]
