#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.3.3
Commit SHA: b0d9a6b14bc1c35549979516f4fdd38feed81cfa
Build Timestamp: 2025-03-21T08:40Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

