# has to be bash for cut to work 
SHELL := /bin/bash

CODENAME := bookworm
ARCH:=amd64

CLIENT := 
CLIENT_FULL_NAME := eth-node-service
VERSION_NUMBER := $(shell dpkg-parsechangelog -l $(CLIENT_FULL_NAME).changelog -S Version 2>/dev/null)
VERSION_NUMBER_WITHOUT_REVISION := $(shell cut -d'-' -f1 <<< $(VERSION_NUMBER))

# double dir, as first dir contains debian tarballs
TARBALL_URL := 
IS_VIRTUAL_PACKAGE := true

# Git source
GIT_SOURCE := 

IS_VIRTUAL_PACKAGE :=  yes