#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.6.0
Commit SHA: d8451e54e7267f9f1634118d6d279b2216f7e2bb
Build Timestamp: 2025-07-22T17:30Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

