#!/bin/bash
set -e

. /usr/share/debconf/confmodule

declare -A CONFIG

adduser --system --quiet --group --home "/var/lib/eth-node-prysm-service-sepolia" eth-node-prysm-service-sepolia

usermod -a -G eth-node-sepolia eth-node-prysm-service-sepolia
if [ "$1" = triggered -a "$service_was_running" '!=' 0 ];
then
	deb-systemd-invoke restart eth-node-prysm-service-sepolia
fi

if [ "$1" '!=' triggered ];
then
	dpkg-trigger eth-node-prysm-service-sepolia-config-changed

fi
#DEBHELPER#

exit 0
