WORK_DIR := /tmp/eth-pkg
SHELL := /bin/bash
CODENAME := bookworm
ARCH:=amd64

CLIENT := teku
CLIENT_FULL_NAME := eth-node-$(CLIENT)
VERSION_NUMBER := $(shell dpkg-parsechangelog -l $(CLIENT_FULL_NAME).changelog -S Version 2>/dev/null | sed 's/-.*//')
# double dir, as first dir contains debian tarballs
TARBALL_URL := https://github.com/Consensys/teku/archive/refs/tags/$(VERSION_NUMBER).tar.gz
# Git source
GIT_SOURCE := https://github.com/Consensys/teku.git


IS_VIRTUAL_PACKAGE := 
