#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path(){
  output="$(which nethermind)"
  assertEquals "/usr/bin/nethermind" "$output"
}

test_invocation_with_dotnet(){
  output="$(nethermind --version)"
  echo "$output"
  # checked against https://github.com/NethermindEth/nethermind/releases/download/1.21.1/nethermind-1.21.1-9b435ba0-linux-x64.zip
  assertContains "Version: 1.21.1+Nethermi" "$output"
  assertContains "Commit: Nethermind" "$output"
  assertContains "OS: Linux x64" "$output"
  # TODO need to fix version to 7.0.18, should be same as actual built Nethermind
  assertContains "Runtime: .NET 7.0.18" "$output"
}

. shunit2