#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version:1.0.6
Commit SHA: c228fe15808c3acbf18dc3af1a03ef5cbdcda07a
Build Timestamp: 2024-08-30T10:55Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

