#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.3.12
Commit SHA: 6f8e7258f4733279080e4bd8345ce50538a40d6e
Build Timestamp: 2025-04-18T07:45Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

