#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path_beacon_chain(){
  output="$(which beacon-chain)"
  assertEquals "/usr/bin/beacon-chain" "$output"
}

test_beacon_chain_invocation(){
  output="$(beacon-chain --version)"
  echo "$output"
  # checked against https://github.com/prysmaticlabs/prysm/releases/download/v4.1.1/beacon-chain-v4.1.1-linux-amd64
  # Note build at information is static, to achieve reproducible builds
  assertEquals "$output" "beacon-chain version Prysm/v5.1.0/b8cd77945df2b8fa8fe50520df0495309a52c2f3. Built at: 2024-08-21 10:01:53+00:00" 
}



. shunit2