WORK_DIR := /tmp/eth-pkg
SHELL := /bin/bash
CODENAME := bookworm
ARCH:=amd64

CLIENT :=geth
CLIENT_FULL_NAME := eth-node-$(CLIENT)
VERSION_NUMBER := $(shell dpkg-parsechangelog -l $(CLIENT_FULL_NAME).changelog -S Version | sed 's/-.*//')
# double dir, as first dir contains debian tarballs
TARBALL_URL := https://github.com/ethereum/go-ethereum/archive/refs/tags/v$(VERSION_NUMBER).tar.gz

# Git source
GIT_SOURCE := https://github.com/ethereum/go-ethereum.git

IS_VIRTUAL_PACKAGE := 