[package_fields]
spec_file = "ethereum-genesis-generator.sss"
package_name = "ethereum-genesis-generator"
version_number = "3.7.0"
revision_number = "1"
homepage="https://github.com/ethpandaops/ethereum-genesis-generator"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "https://github.com/ethpandaops/ethereum-genesis-generator/archive/refs/tags/v3.7.0.tar.gz"
## Provided by debian package maintainer not by team developing the software
tarball_hash = "a24386266fd9f84fd266eebf6b3b00a420a7774a4f4157589396ebfd1afd84ea"

[package_type.language_env]
language_env = "python"

[build_env]
codename="noble numbat"
arch = "amd64"
pkg_builder_version="0.2.11"
debcrafter_version = "8189263"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.28"
sbuild_version="0.85.6"
# package directory
workdir="~/.pkg-builder/packages/noble"
