[verify]
package_hash=[
    { hash="f1aa95db8ea09244cbc6a43597d3da7904a164ec", name= "ethereum-genesis-generator_3.7.0-1.dsc"},
    { hash="00bdd00bf8cf263dda45fbcd385340d55836b4ab", name= "ethereum-genesis-generator_3.7.0.orig.tar.gz"},
    { hash="e4cbd4394e5ad34ec7aadf5337c5ffcf53175f4a", name= "ethereum-genesis-generator_3.7.0-1.debian.tar.xz"},
    { hash="f5aaa522c025e71714705a798027d6ff0c87691b", name= "ethereum-genesis-generator_3.7.0-1_amd64.deb"},
]
