#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version:1.0.1
Commit SHA: d599393771f9d7d137ea4abf271e1bd118184c73
Build Timestamp: 2024-07-09T17:12Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

