#!/usr/bin/env sh

exec 2>&1

set -e

cd /tmp
curl https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb --output jdk-17_linux-x64_bin.deb
dpkg -i jdk-17_linux-x64_bin.deb

test_binary_in_path(){
  output="$(which teku)"
  assertEquals "/usr/bin/teku" "$output"
}

test_invocation(){
  output="$(teku --version)"
  # TODO fix version numbers
  assertEquals "teku/vUNKNOWN+develop/linux-x86_64/oracle-java-17" "$output"
}

. shunit2