#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.3.9
Commit SHA: 00e5b6e01e3cf4c86cb3625f7aff52b81960d724
Build Timestamp: 2025-04-14T15:49Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

