#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.2.2
Commit SHA: 2f4c509b3d01960f96abf2f9314b7d63db36977b
Build Timestamp: 2025-03-05T14:09Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

