#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.2.0
Commit SHA: 1e965caf5fa176f244a31c0d2662ba1b590938db
Build Timestamp: 2025-02-13T15:09Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

