#!/bin/bash
set -e

. /usr/share/debconf/confmodule

declare -A CONFIG

adduser --system --quiet --group eth-node-mainnet-service-lodestar 
mkdir -p /var/lib/eth-node-mainnet/lodestar
chown eth-node-mainnet-service-lodestar:eth-node-mainnet-service-lodestar /var/lib/eth-node-mainnet/lodestar 

if [ "$1" = triggered -a "$service_was_running" '!=' 0 ];
then
	deb-systemd-invoke restart eth-node-mainnet-service-lodestar
fi

if [ "$1" '!=' triggered ];
then
	dpkg-trigger eth-node-mainnet-service-lodestar-config-changed

fi
#DEBHELPER#

exit 0
