name: regtest daily

on:
  workflow_dispatch:
  # Run daily at midnight (UTC time)
  schedule:
    - cron: '0 0 * * *' # 12:00 AM UTC
    - cron: '0 12 * * *'  # 12:00 PM UTC
  


jobs:
  test:
    name: regtest
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        el_name: [besu, geth, nethermind, erigon, reth]
        cl_name: [lighthouse, lodestar, nimbus-eth2, prysm, teku]
        validator_name: [lighthouse, lodestar, nimbus-eth2, prysm, teku]
        exclude: 
        - cl_name: lighthouse 
          validator_name: prysm
      fail-fast: false
     
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: tests
        uses: ./.github/actions/regtest
        with:
          network: regtest
          el_name: ${{matrix.el_name}}
          cl_name: ${{matrix.cl_name}}
          validator_name: ${{matrix.validator_name}}
          build_from_source: "false"
    
