#!/usr/bin/env sh

exec 2>&1

set -e

test_binary_in_path() {
	output="$(which reth)"
	assertEquals "/usr/bin/reth" "$output"
}

test_invocation() {
	output="$(reth --version)"
	echo "$output"
	# checked against https://github.com/paradigmxyz/reth/releases/download/v0.2.0-beta.8/reth-v0.2.0-beta.8-x86_64-unknown-linux-gnu.tar.gz
	assertEquals "$output" "reth Version: 1.1.4
Commit SHA: 15fac0873e91ea29ab2e605bfba17bedcd7a6084
Build Timestamp: 2024-12-11T13:03Z
Build Features: jemalloc
Build Profile: maxperf"
}

. shunit2

